import type { Chapter } from '../types'

const chapter: Chapter = {
  id: 11, slug: 'populating-and-scaling-a-cache', title: 'Populating And Scaling A Cache', module: 'caching',
  estimatedMinutes: 35,
  summary: 'Choose how values enter a cache, how writes invalidate them, and what happens when many callers miss together. Scale the cache without allowing an outage or hot key to overwhelm the database.',
  objectives: ['Compare cache-aside, read-through, write-through, and write-behind.', 'Explain invalidation races and freshness limits.', 'Prevent stampedes and control cold-cache load.', 'Distinguish cache sharding from replication and hot-key mitigation.'],
  quickRevision: ['Cache-aside lets the application load a miss from the source.', 'Read-through moves the loading responsibility into the cache abstraction.', 'Write-through updates the source and cache on the write path; partial failures still need handling.', 'Write-behind acknowledges before the source update and needs durable buffering.', 'Commit the source update before invalidating a cache-aside entry.', 'TTL limits entry lifetime, but stale refills can extend apparent data age.', 'Single-flight combines concurrent loads for one key.', 'TTL jitter spreads expiry across keys; it does not solve one extremely hot key.', 'Sharding divides keys; replication creates more copies of a key.', 'A cache outage needs bounded fallback, not unlimited database traffic.'],
  sections: [
    { id: 'population', title: 'Who loads a missing value?',
      body: `A cache is useful only if it contains the values callers need. In cache-aside, the application checks the cache, reads the source on a miss, then stores the result with an expiry. The application owns the loading code and the decision about which failures should be cached. An ordinary miss is not an error; it is an expected branch of the read path.

Read-through exposes a similar experience through a cache abstraction that invokes a loader. This can centralize loading and error handling, but does not by itself guarantee consistency with concurrent writes. Both strategies usually populate only requested keys, avoiding the cost of copying the entire source into memory.

Consider a catalog with ten million products but only fifty thousand popular today. Loading everything spends memory on unlikely requests and takes longer to recover after restart. Warming a measured popular subset can help, while less common keys load on demand. Cache keys must include every input that changes the result, such as locale, currency, tenant, and relevant permissions. An incomplete key produces wrong answers even with a perfect hit rate.`,
      mentalModel: 'A librarian keeps frequently requested books on a desk. Cache-aside means you fetch a missing book; read-through means the desk attendant fetches it for you.',
      diagram: 'Request -> cache lookup -> hit -> return\n                    |\n                   miss -> source -> cache fill -> return',
      keyPoints: ['Define ownership of miss loading.', 'Warm a useful subset, not necessarily everything.', 'Include result-changing inputs in the key.'],
      checkpoint: { question: 'Two tenants request the same product ID but see different prices. Is product ID alone a safe cache key?', answer: 'No. Include tenant and other price-affecting context, or cache only a shared base record and apply tenant-specific pricing separately.' } },
    { id: 'write-policies', title: 'Decide what an acknowledged write means',
      body: `A read strategy needs a matching write strategy. With cache-aside, a common baseline is to commit the authoritative database change and then invalidate the cached value. The next miss reloads the source. Invalidating first creates a window in which another caller reloads the old database value before the write commits. Reversing the order reduces that race but does not eliminate every stale-fill scenario.

Write-through updates the source and cache as part of the write path. Define ordering, retries, and what happens when only one operation succeeds: two successful network requests are not automatically one atomic transaction. The database normally remains authoritative, and a failed cache operation can be repaired or invalidated.

Write-behind initially accepts data into a buffer and writes the database later. It can smooth bursts or combine repeated updates, but accepted data must survive buffer failure if durability is promised. A memory-only cache is not a durable queue. Preserving ordering also matters: an old delayed write must not overwrite a newer value. Choose write-behind only when those recovery and consistency requirements are understood.`,
      mentalModel: 'Write-through updates the official ledger during the visit. Write-behind gives a receipt for paperwork still waiting in an outbox; losing the outbox loses the promise.',
      diagram: 'Cache-aside write: database commit -> invalidate cache\nWrite-through:    source + cache on acknowledged path\nWrite-behind:     durable buffer -> later source update',
      keyPoints: ['Database-first invalidation is a baseline, not strict consistency.', 'Define partial-failure behavior for writes.', 'Write-behind needs durable, ordered recovery.'],
      checkpoint: { question: 'A cache accepts a write and crashes before flushing it to the database. When is acknowledgment safe?', answer: 'Only if the promised durability is backed by recoverable storage or replication with an explicit failure model. Otherwise the accepted write can disappear; an in-memory buffer alone cannot promise durable success.' } },
    { id: 'invalidation', title: 'A stale fill can arrive after invalidation',
      body: `Imagine reader A misses the cache and reads version 7 from the database. Before A fills the cache, writer B commits version 8 and invalidates the key. A then stores version 7. Every step in the usual database-first invalidation sequence occurred, yet the cache is stale. This is why cache-aside alone does not provide a strict consistency guarantee.

A time to live bounds how long that particular entry remains cached after insertion. It does not necessarily bound the age of the underlying value if a slow reader or lagging replica can refill old data. Versioned values and an atomic comparison against a retained version watermark can reject stale fills, but the design must preserve that watermark even when the cached value is deleted. Some systems avoid the problem on sensitive paths by reading the authoritative source instead.

Invalidation notifications can also be lost. A transactional outbox or change stream can make delivery recoverable, while expiration provides an additional cleanup mechanism. Specify an observable freshness target and test concurrent reads, writes, and message delays. A high cache hit ratio is useful only when the returned data is acceptable.`,
      mentalModel: 'A clerk throws out yesterday’s menu, but a slow courier puts another copy of yesterday’s menu back on the counter.',
      diagram: 'A: read v7 --------------------------> cache SET v7\nB:          commit v8 -> invalidate\nResult: v7 survives until expiry or repair',
      keyPoints: ['Test stale-fill races explicitly.', 'Entry TTL and source-data age differ.', 'Use stronger mechanisms only where the freshness contract needs them.'],
      checkpoint: { question: 'Does a sixty-second TTL guarantee every returned value is less than sixty seconds old?', answer: 'No. TTL measures time since insertion or refresh. A refill from an old snapshot or lagging source can insert data that was already old.' } },
    { id: 'stampedes', title: 'Make a miss cheap for the source',
      body: `Suppose a popular key expires while a thousand callers are reading it. Without coordination, every caller loads the same expensive result from the source. This cache stampede converts a small logical miss into a sudden database spike. Single-flight groups simultaneous loads for the same key so one operation performs the work and others await its result. A per-process implementation reduces duplication within a process; coordinating across processes requires an additional shared mechanism.

Bound waiting time and handle loader failure. A distributed refresh lease must expire if its owner crashes, and a former owner must not overwrite a newer result after its lease expires. For data that tolerates it, serving an explicitly bounded stale value while one refresh runs improves availability and latency.

Randomizing expirations helps when many different keys were populated together and would otherwise expire together. It does not stop thousands of callers missing the same key. Also consider short-lived negative caching for stable not-found results, while distinguishing missing data from temporary errors. During a full cache outage, enforce concurrency limits and load shedding so fallback cannot flood the database.`,
      mentalModel: 'One person goes to the storeroom for a missing item while the queue waits; a thousand people rushing there together create the outage.',
      keyPoints: ['Coalesce concurrent loads per key.', 'Jitter spreads different-key expirations.', 'Bound fallback and distinguish not-found from failures.'],
      checkpoint: { question: 'All keys have randomized TTLs, but one celebrity profile still overloads the database on expiry. Why?', answer: 'Jitter separates expiration times across keys. The single hot key still has many simultaneous misses; use load coalescing, a refresh lease, or permitted stale serving.' } },
    { id: 'scaling', title: 'Capacity, hot keys, and recovery',
      body: `Cache sharding assigns different keys to different nodes, increasing aggregate memory and request capacity when access is sufficiently distributed. A routing scheme such as consistent hashing reduces the fraction of keys that move when membership changes, but moved keys still become cold unless explicitly migrated. Plan how much refill traffic the source can survive during rebalancing.

One hot key remains on one shard, so more shards do not necessarily fix it. Replication, small local caches, or application-level decomposition can spread reads of that key. Each additional copy increases invalidation and freshness work. Measure per-key and per-node traffic rather than relying only on the cluster average.

Memory sizing must include keys, values, metadata, allocator overhead, and any replica copies. Eviction policy should suit the access distribution, and large values can dominate memory and network transfer. Watch hit rate together with source request rate, latency, evictions, and failed loads. Exercise a node restart and a whole-cache outage using bounded warm-up. The real capacity question is whether the application still meets its target while the cache recovers.`,
      mentalModel: 'More cupboards hold more different ingredients, but everyone reaching for the same salt jar still crowds one cupboard.',
      keyPoints: ['Sharding spreads keys; replication spreads copies.', 'Expect refill traffic when membership changes.', 'Measure recovery behavior and source protection.'],
      checkpoint: { question: 'A cache cluster averages thirty percent CPU, yet one shard times out. What should you inspect?', answer: 'Per-key traffic, value sizes, and that shard’s resource use. A hot key or skew can saturate one node while cluster averages look healthy.' } },
  ],
  quiz: [
    { type: 'mcq', id: 'q1', difficulty: 1, question: 'Who fetches from the source in cache-aside?', options: ['The browser DNS resolver', 'The application loading a miss', 'Always the database trigger', 'The eviction policy'], answerIndex: 1, explanation: 'The application explicitly checks the cache, loads the source on a miss, and fills the cache.' },
    { type: 'mcq', id: 'q2', difficulty: 2, question: 'What is the common cache-aside write order?', options: ['Invalidate, then eventually commit', 'Only write the cache', 'Commit the source, then invalidate', 'Delete the database row on every hit'], answerIndex: 2, explanation: 'Committing first avoids a common early-invalidation race, although a concurrent stale fill can still occur.' },
    { type: 'mcq', id: 'q3', difficulty: 2, question: 'What directly reduces duplicate loads for one expiring key?', options: ['Single-flight', 'A longer key name', 'More shards alone', 'Randomizing unrelated keys'], answerIndex: 0, explanation: 'Single-flight combines concurrent loads of the same key. Spreading other keys does not combine these callers.' },
    { type: 'mcq', id: 'q4', difficulty: 2, question: 'What does write-behind require to promise durable acknowledgment?', options: ['No expiry', 'A high hit ratio', 'An LRU policy', 'Recoverable buffering and replay'], answerIndex: 3, explanation: 'The accepted write must survive until the authoritative store is updated. Memory-only buffering cannot guarantee this.' },
    { type: 'multi', id: 'q5', difficulty: 3, question: 'Which can protect a database during cache trouble?', options: ['Bounded fallback concurrency', 'Permitted bounded stale serving', 'Per-key load coalescing', 'Unlimited retries without delay'], answerIndices: [0, 1, 2], explanation: 'The first three limit source work. Unbounded retries amplify overload.' },
    { type: 'truefalse', id: 'q6', difficulty: 2, statement: 'Database-first invalidation removes every stale-fill race.', answer: false, explanation: 'A reader that fetched an older version before the write can fill it after invalidation.' },
    { type: 'truefalse', id: 'q7', difficulty: 1, statement: 'Cache sharding always fixes a single hot key.', answer: false, explanation: 'A key normally still belongs to one shard. Additional copies or key decomposition may be needed.' },
    { type: 'truefalse', id: 'q8', difficulty: 2, statement: 'A cache key may need tenant and locale as well as an entity ID.', answer: true, explanation: 'Every input that changes the cached result must be represented or applied outside the shared cached value.' },
    { type: 'short', id: 'q9', difficulty: 3, question: 'Describe a stale-fill race and one appropriate response.', modelAnswer: 'Reader A fetches v1, writer B commits v2 and invalidates, then A caches v1. For a tolerant path use a bounded expiry and repair strategy with a documented freshness limit. For stronger guarantees use version-aware fills with retained coordination state, or bypass the cache on the sensitive read.', rubric: ['Correct interleaving', 'Acknowledges invalidation alone is insufficient', 'Response matched to freshness needs'] },
    { type: 'short', id: 'q10', difficulty: 3, question: 'Plan a safe restart of a large cache.', modelAnswer: 'Estimate source spare capacity, warm only popular keys at a bounded rate, and coalesce duplicate fills. Apply fallback concurrency limits and load shedding. Watch source latency, failed loads, cache hit rate, and eviction pressure, then gradually restore normal traffic.', rubric: ['Source capacity budget', 'Bounded warm-up and coalescing', 'Overload protection', 'Recovery metrics'] },
  ],
  flashcards: [
    { id: 'f1', front: 'Cache-aside', back: 'Application reads cache, loads source on miss, and fills cache.' },
    { id: 'f2', front: 'Read-through', back: 'A cache abstraction owns a loader invoked on misses. It does not automatically solve consistency races.' },
    { id: 'f3', front: 'Write-through', back: 'Source and cache updates are on the write path. Define partial failures; separate stores are not automatically atomic.' },
    { id: 'f4', front: 'Write-behind', back: 'Buffer an accepted write and update the source later. Durable acknowledgment needs recoverable buffering and ordered replay.' },
    { id: 'f5', front: 'Baseline invalidation order', back: 'Commit the authoritative write, then invalidate. This reduces one race but does not prevent all stale fills.' },
    { id: 'f6', front: 'Stale-fill race', back: 'An older source read fills the cache after a newer write has committed and invalidated the key.' },
    { id: 'f7', front: 'Single-flight', back: 'Coalesce concurrent loads for the same key. Scope can be one process or coordinated across processes.' },
    { id: 'f8', front: 'TTL jitter', back: 'Randomize expiry to avoid many different keys expiring together. It does not eliminate a hot-key stampede.' },
    { id: 'f9', front: 'Negative caching', back: 'Briefly cache a stable missing result to avoid repeated source lookups. Do not confuse temporary errors with absence.' },
    { id: 'f10', front: 'Sharding versus replication', back: 'Sharding divides different keys among nodes. Replication keeps extra copies, potentially spreading reads of the same key.' },
    { id: 'f11', front: 'Cold-cache danger', back: 'Most reads become source loads at once. Bound warm-up and fallback concurrency to protect the source.' },
    { id: 'f12', front: 'Complete cache key', back: 'A key represents every input affecting the cached result, including relevant tenant, locale, currency, or access context.' },
  ],
  feynman: [
    { id: 'fe1', concept: 'Invalidation races', prompt: 'Explain how a cache becomes stale even when a writer invalidates it correctly.', modelExplanation: 'Picture a restaurant assistant copying the menu. While the assistant walks back, the chef changes the official menu and removes the old copy from the counter. The assistant then puts their old copy on the empty counter. The chef followed the expected order, yet customers still see old prices. The database reader and writer can overlap in exactly this way. Expiry limits how long that inserted copy survives, but it does not prove it was fresh when inserted. For ordinary browsing we may accept a stated delay. For a sensitive decision, we can consult the source or use a version-aware system that remembers newer changes and rejects older copies. The important step is to define acceptable freshness before choosing the mechanism.', mustMention: ['Overlapping reader and writer', 'Old fill after invalidation', 'TTL has limits', 'Freshness-driven mitigation'] },
    { id: 'fe2', concept: 'Cache stampede', prompt: 'Explain a stampede and why randomized expiry is only part of the solution.', modelExplanation: 'If everyone asks for the same missing book, sending every person to the warehouse creates a crowd. Single-flight sends one person and lets the others share the returned book. That solves duplicate work for one item. Randomized expiry solves a different problem: it prevents all books on the desk from being removed at exactly noon. Even with staggered removal, a wildly popular book can still attract a crowd when its own copy disappears. We may keep serving a slightly old copy while one person refreshes it, if the content allows that. If the whole desk disappears, we also need an admission limit at the warehouse. Otherwise a cache failure becomes a database failure too.', mustMention: ['Concurrent misses duplicate work', 'Single-flight per key', 'Jitter across keys', 'Bounded source fallback'] },
  ],
  memoryPalace: { setting: 'Tour a library desk, its copying room, and the warehouse behind it.', stops: [
    { locus: 'Desk bell', concept: 'Cache-aside', image: 'A reader rings a bell, finds an empty shelf, and personally fetches a glowing book.' },
    { locus: 'Official ledger', concept: 'Write policies', image: 'One clerk writes immediately while another piles receipts in a fireproof outbox marked LATER.' },
    { locus: 'Copying room', concept: 'Stale fills', image: 'A sleepy courier places a yellow old menu on a freshly cleared counter.' },
    { locus: 'Warehouse doorway', concept: 'Single-flight', image: 'A thousand readers merge into one giant person carrying one book.' },
    { locus: 'Clock wall', concept: 'TTL jitter', image: 'Dozens of clocks ring at different seconds instead of exploding together at noon.' },
    { locus: 'Salt-colored shelf', concept: 'Hot key', image: 'Every visitor crowds one tiny shelf while the other nine cupboards stand empty.' },
  ] },
  interviewQuestions: ['Compare cache-aside, read-through, write-through, and write-behind.', 'Show a stale-fill race despite database-first invalidation.', 'How would you prevent a hot-key stampede?', 'How does cache sharding differ from replication?', 'How would you protect the source during a cache outage?'],
}

export default chapter
