import type { Chapter } from '../types'

const chapter: Chapter = {
  id: 20, slug: 'client-server-model-and-communication-protocols', title: 'Client Server Model And Communication Protocols', module: 'building-blocks',
  estimatedMinutes: 35,
  summary: 'Trace a request through naming, transport, encryption, and application semantics. Choose HTTP, RPC, or live streaming from the interaction contract, and handle the failures that every network protocol leaves to the application.',
  objectives: ['Separate DNS, transport, TLS, and application responsibilities.', 'Compare HTTP versions without confusing transport with API design.', 'Choose request-response, RPC, or streaming interactions.', 'Design deadlines, retries, and idempotent application operations.'],
  quickRevision: ['Client and server are roles in an interaction; a service can be both.', 'DNS resolves names and can return cached answers.', 'TCP provides a reliable ordered byte stream, not application message boundaries.', 'UDP provides datagrams without built-in reliable ordered delivery.', 'TLS protects data in transit and authenticates peers according to its configuration.', 'HTTP semantics include methods, status codes, headers, and representations.', 'HTTP/2 multiplexes streams over TCP; transport loss can affect all streams.', 'HTTP/3 uses QUIC with independent stream delivery over UDP.', 'REST is an architectural style; JSON is a representation format.', 'RPC still crosses a fallible network even when generated code looks local.', 'Use deadlines and idempotency to handle ambiguous results.', 'A successful network send is not proof that a business operation completed.'],
  sections: [
    { id: 'request-journey', title: 'Follow a request through the layers',
      body: `When a browser requests a profile, several systems cooperate. It may resolve a hostname using cached DNS information or a resolver, select an address, establish or reuse a connection, negotiate encryption, and send an application request. The response then travels back through that established path. A warm connection can avoid parts of setup, so the first request and later requests can have different latency profiles.

Client and server describe roles, not permanent machine types. A web service is a server to the browser and a client when it calls a database or another API. Each boundary can introduce waiting, failure, and an independent authentication decision. Drawing these boundaries makes hidden downstream work visible.

DNS does not distribute every individual request after a connection is established. A name resolution answer may be cached, and an existing connection can continue using its selected endpoint. Moving traffic therefore requires considering both name-resolution caching and connection lifetime. Measure setup time, queue time, server processing, and response transfer separately rather than treating every slow request as one undifferentiated network problem.`,
      mentalModel: 'DNS is the address book, the connection is the road, encryption is the sealed vehicle, and the API request is the actual errand.',
      diagram: 'Name -> DNS answer -> connection -> TLS -> application request\nBrowser -> API service -> database\n client     server/client     server',
      keyPoints: ['Different layers solve different problems.', 'Connections and DNS answers can be reused.', 'Services switch client/server roles at boundaries.'],
      checkpoint: { question: 'Does changing a DNS record move an already-open WebSocket immediately?', answer: 'No. The connection remains attached to its existing endpoint until it closes or the protocol performs a supported migration. Cached DNS answers also affect subsequent connections.' } },
    { id: 'transport', title: 'Bytes, datagrams, and encrypted channels',
      body: `TCP gives applications a reliable, ordered stream of bytes while the connection remains viable. It handles retransmission and congestion control, but does not preserve the boundaries of individual application writes. If an application sends two messages, the receiver must still know how to separate them using framing, lengths, or another protocol rule. A connection can also fail without telling the caller whether a remote business operation completed.

UDP sends datagrams and preserves their individual boundaries, but does not itself guarantee arrival, order, or deduplication. Applications or protocols built above it can add those features. It is therefore inaccurate to describe every protocol using UDP as unreliable: QUIC adds reliable streams, flow control, congestion control, and encrypted transport on top of UDP.

TLS protects traffic from observation and modification in transit and authenticates the peer according to certificates and configuration. It does not decide whether the authenticated user is allowed to delete a particular record. Keep channel protection, user authentication, and resource authorization as separate design responsibilities. A secure channel can still carry an invalid or unauthorized application request.`,
      mentalModel: 'TCP is a numbered roll of paper; UDP is individual postcards. Encryption seals the contents, but the recipient still checks whether the requested action is allowed.',
      diagram: 'TCP: bytes -> ordered stream -> application framing\nUDP: datagram A, datagram B -> possible loss/reordering\nQUIC over UDP: reliable independent streams + encryption',
      keyPoints: ['TCP needs application framing.', 'UDP properties are not the full properties of protocols above it.', 'Transport security is separate from authorization.'],
      checkpoint: { question: 'A server reads one TCP chunk. Can it assume that chunk is exactly one application message?', answer: 'No. TCP exposes a byte stream. The application protocol must frame messages and handle partial messages or several messages in one read.' } },
    { id: 'http', title: 'HTTP versions change transport, not the business contract',
      body: `HTTP defines application concepts such as methods, status codes, headers, and representations. A resource-oriented API might use GET to retrieve a document and PUT to replace a resource at a known address. These semantics matter independently of whether the representation is JSON, HTML, or another format. REST is an architectural style, while JSON is only a data format; using JSON over HTTP does not by itself establish every REST constraint.

HTTP/1.1 commonly uses persistent connections, with multiple connections often used for parallel work. HTTP/2 multiplexes streams on one TCP connection and uses a binary framing layer. HTTP/3 maps HTTP semantics onto QUIC. QUIC avoids TCP-level cross-stream head-of-line blocking, although congestion and shared resource limits still affect the connection. None of these versions automatically removes slow database queries or application serialization.

Choose caching and retry rules from the method and operation contract. A GET should not trigger a purchase merely because it is easy to expose as a URL. A status code should communicate a meaningful outcome, while structured error details help clients recover. Version negotiation is infrastructure behavior; business correctness remains an API design responsibility.`,
      mentalModel: 'Changing from road to rail improves how letters travel. It does not change what the words on the order form mean.',
      diagram: 'HTTP semantics: methods + status + headers + representations\n      | HTTP/1.1 or HTTP/2 -> TCP\n      | HTTP/3 -----------> QUIC -> UDP',
      keyPoints: ['Separate semantic contract from transport version.', 'Multiplexing does not remove application bottlenecks.', 'Methods and status codes guide caching and retry behavior.'],
      checkpoint: { question: 'Will moving an API to HTTP/3 fix a database query taking five seconds?', answer: 'Not by itself. HTTP/3 changes transport behavior; the database processing time still needs separate diagnosis and optimization.' } },
    { id: 'interaction-patterns', title: 'Choose the shape of the conversation',
      body: `Request-response works well when a caller asks for a bounded result, such as fetching a profile or submitting an order. Resource-oriented HTTP APIs can integrate with common clients, caches, and debugging tools. RPC expresses interactions as remote operations, often through generated clients and typed schemas. gRPC supports unary calls and several streaming forms, making it useful when a strongly specified service contract and streaming interactions fit the environment.

Generated RPC code can resemble a local function call, but its cost and failure modes are different. Serialization, network delay, deadlines, cancellation, and partial failure still exist. Schema evolution must preserve compatibility between independently deployed clients and servers. Changing a field meaning can be more dangerous than merely adding an optional field.

For live updates, use server-sent events when a one-way server stream fits, or WebSocket when the connection needs bidirectional messages. A durable queue is different again: it decouples when producer and consumer run, often accepting eventual completion instead of an immediate result. Select the interaction from latency, direction, durability, client support, and failure-recovery requirements rather than choosing a protocol because it is fashionable.`,
      mentalModel: 'A counter visit, a phone conversation, and a letter in an outbox are different ways to coordinate the same people.',
      keyPoints: ['Match interaction shape to the product.', 'RPC is still remote and fallible.', 'Streaming and durable asynchronous work solve different needs.'],
      checkpoint: { question: 'A dashboard only needs updates from the server, while edits use ordinary HTTP. Must it use WebSocket?', answer: 'No. Server-sent events may fit the one-way update stream. Consider infrastructure and client requirements before adding a bidirectional connection.' } },
    { id: 'failure-contracts', title: 'Timeouts leave an uncertain outcome',
      body: `Suppose a client submits an order, the server commits it, and the connection fails before the response arrives. The client sees a timeout, but the order exists. Retrying with a fresh identifier may create another order. A safer API accepts an idempotency key, records the result associated with that key, and returns the same logical result for a compatible retry. Define key scope, payload matching, and retention so deduplication behavior is predictable.

A deadline bounds the caller's total waiting time. Propagate the remaining budget downstream instead of allowing every service a fresh full timeout. Cancellation can stop unnecessary work, but it is cooperative and does not automatically undo side effects already committed. The server must still finish or recover any transaction safely.

Retries need a limit, backoff, jitter, and a reason to believe another attempt may succeed. Repeating an invalid request will not repair it. Repeating overload immediately can worsen it. Instrument attempts with request identifiers and trace context so one user operation can be distinguished from several network attempts. A clear failure contract is part of the protocol design.`,
      mentalModel: 'Losing the receipt does not mean the cashier failed to take payment. Bring the same order ticket back instead of placing a new order.',
      keyPoints: ['A timeout can follow a successful commit.', 'Use operation-level idempotency for safe retries.', 'Budget deadlines across the whole request chain.'],
      checkpoint: { question: 'A caller cancels after two seconds. Does that prove a downstream order was rolled back?', answer: 'No. Cancellation may arrive after commit or may not be observed immediately. Query by the operation identifier and design explicit idempotency and transaction handling.' } },
  ],
  quiz: [
    { type: 'mcq', id: 'q1', difficulty: 1, question: 'Which layer resolves a hostname to addressing information?', options: ['JSON', 'TLS authorization', 'HTTP status codes', 'DNS'], answerIndex: 3, explanation: 'DNS handles name resolution. The other concepts concern representations, security, or application outcomes.' },
    { type: 'mcq', id: 'q2', difficulty: 2, question: 'What must an application protocol add to TCP?', options: ['Message framing', 'IP address existence', 'All packet retransmission', 'A guarantee of no server crashes'], answerIndex: 0, explanation: 'TCP provides bytes rather than application message boundaries. It already handles transport retransmission but cannot prevent server failures.' },
    { type: 'mcq', id: 'q3', difficulty: 1, question: 'HTTP/3 runs over which transport?', options: ['Plain UDP with no reliability', 'QUIC', 'Only TCP', 'DNS'], answerIndex: 1, explanation: 'QUIC provides encrypted, reliable streams over UDP; HTTP/3 maps HTTP semantics onto it.' },
    { type: 'mcq', id: 'q4', difficulty: 2, question: 'What makes a retried order submission one logical operation?', options: ['A different URL each time', 'A larger TCP window', 'An application idempotency key and stored result', 'A JSON body alone'], answerIndex: 2, explanation: 'The server must recognize and deduplicate the business operation. Transport and representation choices do not provide that contract.' },
    { type: 'multi', id: 'q5', difficulty: 2, question: 'Which remain relevant when using generated RPC clients?', options: ['Deadlines', 'Schema compatibility', 'Partial network failure', 'Assuming local-function failure behavior'], answerIndices: [0, 1, 2], explanation: 'Generated syntax does not remove remote costs or failures. Treating the call as a local operation hides those risks.' },
    { type: 'truefalse', id: 'q6', difficulty: 1, statement: 'JSON and REST mean the same thing.', answer: false, explanation: 'JSON is a representation format; REST is an architectural style.' },
    { type: 'truefalse', id: 'q7', difficulty: 2, statement: 'TLS alone decides whether a user can delete a particular object.', answer: false, explanation: 'Channel security and peer authentication are distinct from application resource authorization.' },
    { type: 'truefalse', id: 'q8', difficulty: 2, statement: 'A service can act as a server on one boundary and a client on another.', answer: true, explanation: 'An API serves browsers while calling downstream services as their client.' },
    { type: 'short', id: 'q9', difficulty: 3, question: 'Design retry behavior after an order request times out.', modelAnswer: 'Reuse the same scoped idempotency key and compatible payload. The server returns the stored result if the operation committed, or safely performs it once if it did not. Limit retries within an overall deadline with backoff and expose an operation-status lookup for uncertain outcomes.', rubric: ['Acknowledges possible prior commit', 'Same key and payload contract', 'Stored result or status lookup', 'Bounded retry budget'] },
    { type: 'short', id: 'q10', difficulty: 3, question: 'Choose protocols for profile reads, live dashboard updates, and background image processing.', modelAnswer: 'Use HTTP request-response for bounded profile reads, an SSE stream for one-way dashboard updates when supported, and a durable queue for background image jobs. Explain authentication, deadlines, replay or retry, and completion reporting for each boundary.', rubric: ['Request-response for bounded reads', 'Suitable one-way streaming', 'Durable asynchronous jobs', 'Explicit failure contracts'] },
  ],
  flashcards: [
    { id: 'f1', front: 'Client/server roles', back: 'Roles belong to an interaction. A service can serve a browser while calling another service as a client.' },
    { id: 'f2', front: 'DNS caching implication', back: 'Record changes need not affect every new connection immediately, and do not move already-established connections.' },
    { id: 'f3', front: 'TCP framing', back: 'TCP is an ordered byte stream. Applications need framing to identify message boundaries across reads.' },
    { id: 'f4', front: 'UDP', back: 'Datagrams without built-in reliable ordered delivery. Higher-level protocols may add those properties.' },
    { id: 'f5', front: 'TLS versus authorization', back: 'TLS protects the channel and authenticates peers according to configuration. The application still enforces resource permissions.' },
    { id: 'f6', front: 'HTTP/2 multiplexing', back: 'Multiple streams share one TCP connection; transport loss can stall delivery across those streams.' },
    { id: 'f7', front: 'HTTP/3', back: 'HTTP semantics over QUIC, which provides reliable independent streams over UDP with encryption.' },
    { id: 'f8', front: 'REST versus JSON', back: 'REST is an architectural style; JSON is a data representation. Neither implies the other.' },
    { id: 'f9', front: 'RPC caveat', back: 'Generated calls still cross a network and need deadlines, compatibility rules, and partial-failure handling.' },
    { id: 'f10', front: 'SSE versus WebSocket', back: 'SSE carries a server-to-client event stream; WebSocket supports bidirectional messages over a live connection.' },
    { id: 'f11', front: 'Idempotency key', back: 'Identifies one logical operation across retries. Scope, payload matching, and result retention must be defined.' },
    { id: 'f12', front: 'Deadline propagation', back: 'Pass remaining time downstream so nested calls stay within the original overall waiting budget.' },
  ],
  feynman: [
    { id: 'fe1', concept: 'Network layers', prompt: 'Explain a web request to someone who thinks the internet is one protocol.', modelExplanation: 'Sending a web request is like arranging a delivery. First an address book tells you where the named business can be found. That is the role of DNS. A transport protocol then carries data between endpoints. Encryption protects what travels and helps establish who is at the other end. Finally, the application protocol describes the request itself: which resource you want, which action you ask for, and what outcome came back. These pieces cooperate but are not interchangeable. A faster road cannot fix a warehouse taking hours to find an item. A sealed package does not grant permission to withdraw money. Diagnosing the right layer helps us choose a useful improvement and avoid claiming guarantees that belong elsewhere.', mustMention: ['Naming', 'Transport', 'Encryption', 'Application semantics remain separate'] },
    { id: 'fe2', concept: 'Ambiguous outcomes', prompt: 'Explain why a timeout does not mean an operation failed.', modelExplanation: 'Suppose you place an order at a counter and the cashier records it, but a loud noise prevents you from hearing the confirmation. From your perspective the conversation failed; from the shop’s perspective the order succeeded. A network timeout is similarly ambiguous. If you place a completely new order, you may get two. Instead, give the original order a unique ticket and reuse that ticket when asking again. The shop remembers the result and returns it without repeating the action. An API idempotency key implements this idea. The contract must explain how long tickets are remembered and reject incompatible requests reusing the same ticket. Retries also need a waiting budget so a broken service does not receive an endless queue of repeat attempts.', mustMention: ['Commit may precede timeout', 'Stable operation identifier', 'Stored result and matching payload', 'Bounded retries'] },
  ],
  memoryPalace: { setting: 'Follow a parcel from an address book through a delivery office.', stops: [
    { locus: 'Address book', concept: 'DNS', image: 'A cached address sticks to your hand even after a clerk updates the main book.' },
    { locus: 'Paper conveyor', concept: 'TCP framing', image: 'A continuous paper roll needs scissors at marked message boundaries.' },
    { locus: 'Sealed van', concept: 'TLS', image: 'A transparent thief cannot see inside the sealed van, but the bank still asks for permission.' },
    { locus: 'Rail switch', concept: 'HTTP versions', image: 'The same order form travels by several different tracks without changing its words.' },
    { locus: 'Telephone desk', concept: 'RPC', image: 'A button looks local but stretches into a long cable across a stormy ocean.' },
    { locus: 'Receipt window', concept: 'Idempotency', image: 'The cashier stamps the same ticket once despite a hundred repeated requests.' },
  ] },
  interviewQuestions: ['Trace the layers involved in a browser request.', 'What does TCP guarantee and what does it leave to the application?', 'Compare HTTP/1.1, HTTP/2, and HTTP/3.', 'When would you choose HTTP APIs, gRPC, SSE, or WebSocket?', 'How do you make retries safe after an ambiguous timeout?'],
}

export default chapter
