import type { Chapter } from '../types'

const chapter: Chapter = {
  id: 21, slug: 'blob-storages-and-s3', title: 'Blob Storages And S3', module: 'building-blocks',
  estimatedMinutes: 35,
  summary: 'Store large bytes separately from searchable application records. Design direct uploads, metadata publication, delivery, and lifecycle cleanup while understanding object storage consistency and access control.',
  objectives: ['Compare object, file, and block storage.', 'Design an authorized direct-upload workflow.', 'Handle partial uploads and metadata publication safely.', 'Plan object delivery, lifecycle, and recovery.'],
  quickRevision: ['An object combines bytes, metadata, and a key in a bucket.', 'Object storage is not a general-purpose POSIX filesystem.', 'Keep searchable business metadata in a suitable database.', 'Presigned URLs delegate a specific storage operation for limited time.', 'Treat presigned URLs as bearer capabilities and scope them narrowly.', 'Multipart upload retries individual parts before completing the object.', 'Verify an uploaded object before publishing its application record.', 'S3 provides strong consistency for object writes, deletes, and listing; external caches remain separate.', 'Strong object consistency does not create a transaction with your database.', 'Use immutable object keys to simplify caching and version changes.', 'Lifecycle rules clean up abandoned parts and old data.', 'Durability, availability, and independent recovery are different concerns.'],
  sections: [
    { id: 'storage-model', title: 'Objects are addressed blobs, not rows or disks',
      body: `A blob is a collection of bytes whose internal meaning belongs to the application: a photo, video, document, or compressed data file. Object storage stores those bytes under a key, along with metadata. Applications commonly retrieve or replace an object through an API rather than opening it as a local file and changing arbitrary bytes in place. Prefixes can organize keys, but a familiar folder display does not imply full filesystem semantics.

Compare this with block storage, which exposes addressable blocks that a filesystem or database can use, and file storage, which exposes file and directory operations. The right model follows the workload. A database engine usually needs storage semantics different from a public image archive. Large media objects often fit object storage well because the application mostly writes them once and reads them many times.

Keep searchable business metadata separate when necessary. A database row can record owner, content type, size, moderation state, and object key, while the object store holds the bytes. The object key is a reference, not proof of ownership. Access decisions belong to the application and storage permission model.`,
      mentalModel: 'Object storage is a warehouse of sealed labeled crates. A database is the searchable inventory telling you who owns each crate and whether it may be shipped.',
      diagram: 'Database: asset_id | owner | status | object_key\n                                      |\nObject storage: bucket / key --------> bytes + metadata',
      keyPoints: ['Choose storage semantics from access patterns.', 'Separate large bytes from searchable records.', 'A key does not grant ownership.'],
      checkpoint: { question: 'Should a media application scan every object to find all photos belonging to a user?', answer: 'Usually no. Query indexed ownership metadata in a database and use the resulting object keys to retrieve the bytes.' } },
    { id: 'direct-upload', title: 'Authorize uploads without proxying every byte',
      body: `Sending a large video through an application server consumes its bandwidth, memory buffers, and connection time before the object store receives anything. A direct-upload workflow separates permission from byte transfer. The client asks the API to create an upload intent. The API authenticates the user, checks quotas and allowed content, chooses an object key, and returns narrowly scoped upload authorization such as a presigned URL.

The client then sends bytes directly to storage. A presigned URL carries authority, so anyone possessing it may be able to perform the signed operation until its effective expiry or another policy restriction intervenes. Avoid placing it in analytics logs or sharing it as a permanent public link. Restrict the key and operation, and use supported policy conditions or post-upload verification for size and content constraints.

After transfer, the client asks the API to finalize the upload. The API verifies the expected object and metadata before exposing it to others. Client claims alone are not enough: a user could skip the upload, upload the wrong content, or attempt to finalize an object belonging to someone else.`,
      mentalModel: 'The warehouse office issues a temporary loading permit for one assigned bay. The truck goes directly there, and the office inspects the delivery before listing it for sale.',
      diagram: 'Client -> API: create upload intent\nClient <- API: scoped upload authorization\nClient -> object store: bytes\nClient -> API: finalize -> verify -> publish',
      keyPoints: ['Separate control requests from bulk transfer.', 'Scope delegated authorization to an intended object.', 'Verify before publication.'],
      checkpoint: { question: 'Can finalize simply trust a client-provided object key?', answer: 'No. Look up the authenticated user’s upload intent and verify the assigned key, object existence, size, and required content checks before marking it ready.' } },
    { id: 'multipart-and-state', title: 'Recover partial transfers and incomplete workflows',
      body: `A large upload should not have to restart from byte zero after one interrupted connection. Multipart upload divides an object into parts that can be uploaded independently, potentially in parallel. The client records the upload identifier and successful part information, retries missing parts, then submits a completion request. Until completion, uploaded parts are not the final published object. Abandoned parts need explicit abort or lifecycle cleanup because they continue consuming storage.

The application also has a multi-step state machine: pending, uploaded, verifying, ready, or failed. Those states describe the product workflow rather than the transport alone. A completed object might still require a malware scan, thumbnail generation, or validation before it becomes visible. Retried finalize calls should be idempotent and refer to the same upload intent.

There is no automatic transaction covering the object store and a separate metadata database. A crash can leave an object without a ready row or a pending row whose transfer never finished. Use reconciliation jobs to find and repair or expire these states. Retain enough identifiers to associate each orphan with its original intent safely.`,
      mentalModel: 'A furniture delivery arrives in numbered boxes. Receiving every box is separate from assembling and approving the furniture for the showroom.',
      diagram: 'Parts 1 + 2 + 3 -> complete object\npending -> uploaded -> verifying -> ready\n    \-> expired/failed -> cleanup or retry',
      keyPoints: ['Retry parts instead of whole large transfers.', 'Model application publication separately.', 'Reconcile orphan objects and stale intents.'],
      checkpoint: { question: 'The object upload completes but the API crashes before marking the row ready. Is the object necessarily lost?', answer: 'No. The object can remain in storage. An idempotent finalize retry or reconciliation job can verify it and advance the existing intent safely.' } },
    { id: 'reads-and-consistency', title: 'Serve bytes without confusing consistency layers',
      body: `Public assets can be delivered through a CDN so repeated reads avoid the origin and travel a shorter network path. Private assets require authorization at the chosen delivery boundary, such as short-lived signed access or an authenticated gateway. A publicly accessible bucket is not necessary for a CDN-backed design; origin access can remain restricted while the delivery layer enforces the intended policy.

Immutable keys simplify cache behavior. Instead of replacing avatar.jpg in place, upload a new versioned key and update the profile record to reference it. Old cached bytes remain associated with the old key, while new references point to the new asset. Define when old versions are deleted and whether cached copies may outlive a permission change.

S3 has strong consistency for supported object writes, deletes, and listing operations, but that does not invalidate a browser or CDN cache and does not coordinate a transaction with your metadata database. Distinguish the storage guarantee from your complete read path. Range requests can retrieve portions of a large object when supported, helping media delivery and resumable downloads without fetching the entire file.`,
      mentalModel: 'The warehouse inventory may update immediately while a billboard still shows yesterday’s picture. Changing the labeled crate and changing the billboard are separate actions.',
      keyPoints: ['CDNs and clients add independent caches.', 'Immutable keys reduce overwrite ambiguity.', 'Storage consistency does not span the application database.'],
      checkpoint: { question: 'S3 immediately reflects a replaced image, but users still see the old one. What else should you inspect?', answer: 'Browser and CDN caching, the metadata record’s object reference, and cache-control policy. Strong origin consistency does not purge external caches.' } },
    { id: 'lifecycle-and-recovery', title: 'Keep storage costs and recovery intentional',
      body: `Storage cost includes more than the bytes currently visible in the product. Old object versions, incomplete multipart uploads, retained backups, request volume, and data transfer can all contribute. Choose lifecycle rules from retention and access requirements. Infrequently accessed storage classes may have retrieval delay, request costs, or minimum-duration considerations, so cheap stored bytes do not necessarily mean a cheap interactive download path.

Versioning can preserve older object versions after an overwrite or deletion, depending on the operation and configuration. It supports recovery but also accumulates data. Replication to another location can improve resilience, yet it is a separate process with its own timing and rules. Neither feature excuses testing how the application restores metadata references and access permissions together with the bytes.

Define retention for failed uploads, deleted assets, and old immutable keys. Cleanup should avoid deleting an object that is still referenced by a live record or active upload. Use conservative age thresholds and reconciliation rather than guessing from a filename alone. Exercise accidental deletion recovery and incomplete-upload cleanup, then monitor storage growth and retrieval performance over time.`,
      mentalModel: 'A warehouse needs a return policy and an archive plan, or abandoned deliveries and every old edition eventually fill the building.',
      keyPoints: ['Include versions, requests, and transfer in cost estimates.', 'Match storage class to retrieval needs.', 'Coordinate cleanup and recovery with metadata.'],
      checkpoint: { question: 'Why can storage usage grow even though users delete visible files?', answer: 'Old versions, incomplete multipart uploads, retained replicas, or delayed cleanup can remain billable. Inspect lifecycle and version-retention behavior alongside application metadata.' } },
  ],
  quiz: [
    { type: 'mcq', id: 'q1', difficulty: 1, question: 'What belongs naturally in an object store?', options: ['A large uploaded video', 'An in-process mutex', 'A CPU register', 'A relational join plan'], answerIndex: 0, explanation: 'Large addressed byte objects fit the object-storage model. The other items are unrelated runtime or query concepts.' },
    { type: 'mcq', id: 'q2', difficulty: 2, question: 'What should happen before issuing upload authorization?', options: ['Make the whole bucket public', 'Trust any client-selected owner', 'Authenticate and create a scoped upload intent', 'Delete old database backups'], answerIndex: 2, explanation: 'The API must establish ownership, quota, and the intended object operation before delegating byte transfer.' },
    { type: 'mcq', id: 'q3', difficulty: 2, question: 'What is a key benefit of multipart upload?', options: ['No cleanup is needed', 'Retry individual failed parts', 'Every part is automatically a published asset', 'No application state is needed'], answerIndex: 1, explanation: 'Parts can be retried independently. Completion, publication, and abandoned-part cleanup remain necessary.' },
    { type: 'mcq', id: 'q4', difficulty: 2, question: 'Why use immutable asset keys?', options: ['To bypass authorization', 'To disable all caching', 'To make objects transactional with SQL', 'To give each content version an unambiguous cache identity'], answerIndex: 3, explanation: 'New content gets a new key, avoiding overwrite ambiguity in external caches. It does not remove permissions or cross-store coordination.' },
    { type: 'multi', id: 'q5', difficulty: 3, question: 'What should finalize verify?', options: ['The upload belongs to the caller', 'The assigned object exists', 'Required size and content checks pass', 'Only that the client says success'], answerIndices: [0, 1, 2], explanation: 'Publication must rely on authorized intent and verified storage state, not client assertions alone.' },
    { type: 'truefalse', id: 'q6', difficulty: 2, statement: 'Strong S3 object consistency automatically purges CDN caches.', answer: false, explanation: 'CDN and browser caches have independent freshness policies.' },
    { type: 'truefalse', id: 'q7', difficulty: 1, statement: 'Anyone holding a valid presigned URL may be able to perform its delegated operation.', answer: true, explanation: 'It is a bearer capability subject to its signature, expiry, credentials, and applicable policies.' },
    { type: 'truefalse', id: 'q8', difficulty: 2, statement: 'A separate SQL row and S3 object are automatically committed atomically.', answer: false, explanation: 'The application must handle partial completion between independent stores.' },
    { type: 'short', id: 'q9', difficulty: 3, question: 'Design a reliable direct upload for private documents.', modelAnswer: 'Authenticate, create a pending intent with an assigned key, issue scoped upload authorization, and upload directly. Finalize verifies ownership, object size, and content checks, then publishes the metadata. Serve through authorized access and reconcile abandoned intents and orphan objects.', rubric: ['Authorized scoped intent', 'Direct transfer', 'Verified idempotent finalize', 'Private delivery and cleanup'] },
    { type: 'short', id: 'q10', difficulty: 3, question: 'How do you investigate unexpected object-storage growth?', modelAnswer: 'Compare visible asset size with stored versions, unfinished multipart parts, retained replicas, and orphan objects. Review lifecycle rules and retention obligations, then reconcile against live metadata before deleting anything. Include request and transfer costs in the broader cost diagnosis.', rubric: ['Hidden retained data categories', 'Lifecycle review', 'Safe metadata reconciliation', 'Broader cost components'] },
  ],
  flashcards: [
    { id: 'f1', front: 'Object', back: 'Bytes plus metadata addressed by a key within a bucket.' },
    { id: 'f2', front: 'Object versus block storage', back: 'Object APIs operate on addressed blobs. Block storage exposes blocks usable by a filesystem or database engine.' },
    { id: 'f3', front: 'Metadata database', back: 'Indexes application fields such as ownership, status, and content type, while referencing object keys for bytes.' },
    { id: 'f4', front: 'Direct upload', back: 'The API authorizes an upload; the client sends bulk bytes directly to storage and later finalizes the intent.' },
    { id: 'f5', front: 'Presigned URL', back: 'Time-limited delegated authority for a specified operation. Treat it as a bearer capability and restrict its scope.' },
    { id: 'f6', front: 'Multipart upload', back: 'Upload independent parts, retry failed parts, then complete the object. Abandoned parts need cleanup.' },
    { id: 'f7', front: 'Finalize step', back: 'Verify ownership and stored content before making an uploaded asset visible to the application.' },
    { id: 'f8', front: 'Cross-store partial failure', back: 'An object may exist without a ready database row, or a row without completed bytes. Use idempotency and reconciliation.' },
    { id: 'f9', front: 'Immutable asset key', back: 'A new content version gets a new key, simplifying CDN and browser cache identity.' },
    { id: 'f10', front: 'S3 consistency boundary', back: 'Strong consistency applies to supported object operations; it does not create SQL transactions or invalidate external caches.' },
    { id: 'f11', front: 'Lifecycle policy', back: 'Rules for retention, transition, and cleanup, including old versions and incomplete uploads.' },
    { id: 'f12', front: 'Storage recovery', back: 'Restore both bytes and correct application references and permissions; durable storage alone is not a complete recovery workflow.' },
  ],
  feynman: [
    { id: 'fe1', concept: 'Direct upload', prompt: 'Explain why the app gives an upload permit instead of carrying every video itself.', modelExplanation: 'A warehouse office should decide which deliveries are allowed, but it does not need to carry every box through its own small room. The application API plays the office role. It authenticates the user, checks limits, assigns a storage location, and gives a temporary permit for that delivery. The client then sends the large bytes directly to storage. Afterward, the office checks that the expected shipment arrived and meets the rules before marking it ready. This keeps application servers focused on decisions instead of bulk transfer. The permit must be narrowly scoped because anyone holding it may be able to use it. Upload completion and product publication remain different steps, especially when content needs verification or processing.', mustMention: ['Separate authorization from byte transfer', 'Scoped temporary permission', 'Verify uploaded content', 'Publish only when ready'] },
    { id: 'fe2', concept: 'Cross-store consistency', prompt: 'Explain why a completed upload can still need reconciliation.', modelExplanation: 'Imagine a truck has delivered a crate, but the office computer crashes before updating the inventory. The crate is real even though the inventory says pending. The reverse can also happen: an inventory record is created, but the truck never arrives. Object storage and an application database are separate systems, so one does not automatically commit together with the other. Model the upload as a sequence of states and make repeated completion requests safe. A reconciliation worker checks old pending records and unreferenced objects, then finishes or cleans up the workflow according to policy. Even strong consistency inside the warehouse does not update the office database for you. Recovery requires matching the bytes with the correct owner, status, and permissions.', mustMention: ['Independent stores', 'Partial completion', 'Idempotent state transitions', 'Reconciliation with ownership'] },
  ],
  memoryPalace: { setting: 'Tour a warehouse from its permit office to the archive basement.', stops: [
    { locus: 'Sealed crates', concept: 'Objects', image: 'Every giant crate carries a glowing key while its contents remain sealed.' },
    { locus: 'Inventory desk', concept: 'Metadata', image: 'A tiny searchable card points to a huge movie reel in another building.' },
    { locus: 'Permit window', concept: 'Presigned URL', image: 'A loading permit melts after its timer expires and opens only one assigned bay.' },
    { locus: 'Assembly floor', concept: 'Multipart', image: 'Three numbered furniture boxes combine only when the foreman stamps COMPLETE.' },
    { locus: 'Inspection lamp', concept: 'Finalize', image: 'A bright lamp keeps a newly arrived crate behind a barrier until its owner and contents are checked.' },
    { locus: 'Archive basement', concept: 'Lifecycle', image: 'Old crate versions pile to the ceiling while a calendar-driven broom carefully avoids live inventory.' },
  ] },
  interviewQuestions: ['When would you choose object storage over file or block storage?', 'Design a secure direct-upload workflow.', 'How do multipart uploads recover from interruption?', 'What does strong object consistency not guarantee?', 'How would you clean up orphan uploads and recover deleted assets?'],
}

export default chapter
