import type { Chapter } from '../types'

const chapter: Chapter = {
  id: 25, slug: 'designing-e-commerce-product-listing', title: 'Designing E-Commerce Product Listing', module: 'case-studies',
  estimatedMinutes: 40,
  summary: 'Design browsing, search, filters, and pagination for a large catalog. Separate the authoritative product record from search projections, and keep price and inventory decisions correct when those projections lag.',
  objectives: ['Define listing requirements and freshness budgets.', 'Design catalog records and searchable projections.', 'Implement stable pagination under concurrent updates.', 'Handle indexing lag, hot queries, and stale availability.'],
  quickRevision: ['Clarify search, filters, sorting, variants, and personalization before choosing storage.', 'The catalog store is authoritative; a search index is a derived read model.', 'Use product IDs and source versions to make indexing idempotent.', 'Persist change intent with the product write to avoid dual-write gaps.', 'Listing freshness and checkout correctness are different contracts.', 'Recheck price and stock on the authoritative purchase path.', 'Deep offset pagination makes shards process increasingly large prefixes.', 'Cursor pagination needs a deterministic sort and a unique tie-breaker.', 'A point-in-time search view stabilizes pagination across changing documents.', 'Cache keys include filters, sort, locale, currency, and relevant audience.', 'Rebuild indexes beside the serving index and switch after verification.', 'Measure indexing lag and relevance alongside API latency.'],
  sections: [
    { id: 'requirements', title: 'Define what a product listing promises',
      body: `Start with a shopper action: search for running shoes, filter by size and brand, sort by price, and open another page. Clarify whether results represent products or individual variants. A shoe might have one product identity but several sizes with different stock. Decide how unavailable variants affect filtering and what price a product card displays when its variants differ.

Separate functional behavior from quality targets. The example design assumes ten million products, read-heavy traffic, and listing updates visible within several seconds. These are exercise assumptions, not measurements from a real retailer. A checkout decision has a stricter contract: it must confirm the actual price and reserve available stock, even if the listing is allowed to lag.

List the query dimensions early: text relevance, category, brand, attributes, locale, currency, sort mode, and any personalized ranking. These determine indexing and cache design. Also define empty results, unavailable filters, and pagination behavior. A system that responds quickly but silently ignores a selected size is not meeting the search requirement.`,
      mentalModel: 'The shop window helps customers discover items; the checkout counter confirms what can actually be sold now.',
      diagram: 'Browse/search -> listing view: bounded freshness\nSelect variant -> detail view\nBuy -> authoritative price + inventory reservation',
      keyPoints: ['Define product and variant semantics.', 'State scale and freshness assumptions.', 'Separate discovery from purchase correctness.'],
      checkpoint: { question: 'A listing says one shoe is in stock, but another user buys it first. Must the listing database serialize both purchases?', answer: 'No. The purchase path must authoritatively reserve inventory. The listing can have a documented freshness delay while checkout prevents overselling.' } },
    { id: 'data-and-projection', title: 'Write a catalog, serve a search projection',
      body: `Store canonical products, variants, prices, and lifecycle state in an authoritative data model. A search projection denormalizes the fields needed for text matching, faceting, filtering, and sorting. This avoids making every listing request execute a large transactional join and allows the search representation to evolve separately from the write model.

The difficult part is keeping the projection updated. Writing a database row and then independently publishing an event can lose the event if the process crashes between those steps. A transactional outbox records the product change and publication intent in the same transaction; a relay delivers events afterward. Change-data capture is another possible integration approach. Neither removes the need for idempotent consumers.

Carry a stable product identifier and source version. An indexer can ignore an older update that arrives after a newer one, and deletion events need version-aware handling too. Keep failed events observable and replayable. Periodic reconciliation can compare authoritative records with indexed versions. The index is useful precisely because it can be rebuilt from reliable source data rather than becoming an undocumented second authority.`,
      mentalModel: 'The inventory ledger is official; the searchable display cards are copies optimized for customers. A numbered dispatch book ensures every ledger change reaches the display team.',
      diagram: 'Catalog transaction -> product rows + outbox\nOutbox relay -> event stream -> indexer -> search index\n                              versions + retry + reconciliation',
      keyPoints: ['Treat search as a rebuildable projection.', 'Close the database/event dual-write gap.', 'Reject out-of-order versions and replay failures.'],
      checkpoint: { question: 'Version 12 reaches the index before version 11. What should the indexer do with version 11?', answer: 'Ignore the stale update using a source-version comparison. Arrival order alone must not decide which catalog state wins.' } },
    { id: 'query-and-pagination', title: 'Return the next page without hidden gaps',
      body: `A listing API validates query inputs, builds a search request, and returns product cards plus pagination information. Filtering and text ranking can be performed by a search engine with suitable indexes. Facet counts should reflect a defined filter context; decide whether a selected facet counts alternatives within its own dimension or only the fully filtered result set.

Offset pagination is simple, but deep pages require increasing amounts of skipped work. Cursor-based pagination continues after the last result's sort values. Use a deterministic sort with a unique tie-breaker, such as price followed by product ID. Price alone is insufficient because many products can share it. The cursor should bind to the query and sort configuration so it cannot accidentally continue a different result set.

Concurrent changes can still cause duplicates or omissions when records move across the cursor boundary. For a stable browsing session, a search engine point-in-time view combined with search-after can preserve a consistent index view. Such snapshots consume resources and expire, so provide an explicit restart path for an expired cursor. Stable pagination is a contract with a cost, not merely an encoded offset.`,
      mentalModel: 'A bookmark works only when the book order is known. If pages are rearranged mid-read, you need a snapshot of the edition you started.',
      diagram: 'Query + filters + sort -> search view\nPage 1: ... (price=50, id=900) -> cursor\nPage 2: continue after (50,900) in the same view',
      keyPoints: ['Avoid deep skipped prefixes.', 'Use complete sort values and a tie-breaker.', 'Handle changing data and cursor expiration.'],
      checkpoint: { question: 'Why is a cursor containing only price=50 ambiguous?', answer: 'Many products may share that price. Include a unique tie-breaker and the complete sort context; use a stable view if pagination must remain consistent across updates.' } },
    { id: 'caching-and-ranking', title: 'Cache the shared work, preserve query meaning',
      body: `Many shoppers repeat popular category and filter combinations. Cache those result IDs or rendered cards when the freshness budget permits. The cache key must distinguish all inputs affecting the result: query normalization, filters, sort order, locale, currency, and any audience or personalization dimension. Sharing a personalized result under a global key can return inappropriate or private recommendations to another user.

Separate relatively stable catalog details from fast-changing stock and price where useful. Hydrating a page of result IDs can refresh selected fields, but it should use bounded batched reads rather than one network request per product. Decide what happens if hydration discovers a deleted product: omit it, replace it, or report a shorter page according to the API contract.

Ranking is also part of quality. Text relevance, popularity, availability, and commercial rules can compete. Keep an understandable baseline and evaluate changes against representative queries and user outcomes. A high cache hit rate is not a success if shoppers cannot find relevant items. Monitor zero-result rates, indexing delay, expensive queries, and product click-through alongside latency and backend resource use.`,
      mentalModel: 'A preprinted shopping guide is useful only if its language, currency, and audience match the reader holding it.',
      keyPoints: ['Include all result-changing inputs in cache identity.', 'Batch hydration and define missing-item behavior.', 'Evaluate relevance as well as speed.'],
      checkpoint: { question: 'Two users share the same text query but have personalized ranking. Can their complete result pages always share one cache key?', answer: 'No. Include the relevant audience context or cache only the common candidate set before applying personalized ranking.' } },
    { id: 'failure-and-rebuild', title: 'Rebuild safely and degrade honestly',
      body: `Search indexes need schema changes, backfills, and occasional full rebuilds. Build a new index beside the serving one, record a source watermark, load a consistent snapshot, and apply changes after that watermark. Verify document coverage, version progress, and representative query behavior before switching the read alias or routing configuration. Keep a rollback path until the new index is trusted.

During indexing delay, expose appropriate operational signals and preserve the freshness contract. A source outage may leave a still-useful search view, while a search outage may permit a limited cached category experience. Do not silently return an unfiltered generic list while pretending the original request succeeded. Failure behavior should preserve query meaning or clearly state that the requested operation is unavailable.

Hot categories and expensive filters need query limits, timeouts, caching, and capacity planning. Deleted or blocked products need a removal path that considers both the index and caches. Authoritative checkout validation remains necessary even in normal operation. Test an out-of-order update, a lost indexer worker, a rebuild during active writes, and an expired pagination cursor to make these boundaries concrete.`,
      mentalModel: 'Replace the store directory by printing and checking a new edition while customers keep using the old one, then switch the stands together.',
      keyPoints: ['Rebuild beside the serving index.', 'Catch up from a known source position.', 'Degrade without misrepresenting filters or availability.'],
      checkpoint: { question: 'Why is copying yesterday’s catalog into a new index and switching immediately unsafe?', answer: 'Changes since the snapshot can be missing. Capture a watermark, replay subsequent updates, verify coverage and query behavior, then switch with a rollback plan.' } },
  ],
  quiz: [
    { type: 'mcq', id: 'q1', difficulty: 2, question: 'Which component should decide whether the final unit can be purchased?', options: ['A cached search result', 'The authoritative inventory reservation path', 'A product thumbnail', 'A browser facet count'], answerIndex: 1, explanation: 'Listings can lag. The purchase path enforces current inventory and price invariants.' },
    { type: 'mcq', id: 'q2', difficulty: 2, question: 'What closes a database-write/event-publication gap?', options: ['A transactional outbox', 'A larger page size', 'A shorter product title', 'Sorting by price'], answerIndex: 0, explanation: 'The outbox records the source change and event intent atomically, then publishes recoverably.' },
    { type: 'mcq', id: 'q3', difficulty: 2, question: 'What is missing from a cursor containing only price?', options: ['The CSS theme', 'A random server hostname', 'A unique tie-breaker', 'An image checksum'], answerIndex: 2, explanation: 'Equal prices need a deterministic secondary key to define the continuation boundary.' },
    { type: 'mcq', id: 'q4', difficulty: 3, question: 'An old product event arrives after a new one. What should decide whether it is applied?', options: ['Arrival time only', 'The worker name', 'The largest payload', 'The source version'], answerIndex: 3, explanation: 'Source versions prevent delayed updates from overwriting newer indexed state.' },
    { type: 'multi', id: 'q5', difficulty: 2, question: 'Which can affect a listing cache key?', options: ['Locale and currency', 'Selected filters', 'Sort and personalization context', 'Only the unnormalized search text'], answerIndices: [0, 1, 2], explanation: 'Every input that changes the result must be represented or applied outside the cached shared result.' },
    { type: 'truefalse', id: 'q6', difficulty: 2, statement: 'A search index should be the only copy of canonical product data in this design.', answer: false, explanation: 'The design uses a rebuildable search projection derived from authoritative catalog records.' },
    { type: 'truefalse', id: 'q7', difficulty: 2, statement: 'Cursor pagination alone guarantees a stable result set while sort fields change.', answer: false, explanation: 'Moving records can cross the cursor boundary. A consistent view or an explicitly weaker pagination contract is needed.' },
    { type: 'truefalse', id: 'q8', difficulty: 1, statement: 'Listing latency and search relevance are separate quality dimensions.', answer: true, explanation: 'Fast irrelevant results still fail the discovery task.' },
    { type: 'short', id: 'q9', difficulty: 3, question: 'Plan an index rebuild while catalog writes continue.', modelAnswer: 'Create a parallel index from a consistent source snapshot and record its watermark. Replay later changes with source-version checks, validate coverage and representative queries, then switch an alias with rollback available.', rubric: ['Parallel serving/rebuild indexes', 'Snapshot and watermark', 'Catch-up and version handling', 'Validation and rollback'] },
    { type: 'short', id: 'q10', difficulty: 3, question: 'Design stable price-sorted pagination.', modelAnswer: 'Sort by price and unique product ID, bind the cursor to filters and sort, and continue after the full sort tuple. Use a point-in-time index view when stable sessions are required. Expire the cursor explicitly and provide a restart path.', rubric: ['Unique tie-breaker', 'Query-bound cursor', 'Concurrent-update strategy', 'Expiration behavior'] },
  ],
  flashcards: [
    { id: 'f1', front: 'Listing versus checkout', back: 'Discovery may tolerate bounded stale data; checkout must authoritatively validate price and reserve stock.' },
    { id: 'f2', front: 'Search projection', back: 'A denormalized, rebuildable representation optimized for text search, filters, facets, and sorting.' },
    { id: 'f3', front: 'Transactional outbox', back: 'Commit the product change and publication intent together, then relay events recoverably.' },
    { id: 'f4', front: 'Index source version', back: 'A version carried with updates so consumers reject delayed older state and handle retries idempotently.' },
    { id: 'f5', front: 'Deep offset cost', back: 'The engine processes increasingly large skipped prefixes to reach later pages.' },
    { id: 'f6', front: 'Cursor sort tuple', back: 'All sort values plus a unique tie-breaker identify the exact continuation boundary.' },
    { id: 'f7', front: 'Point-in-time search', back: 'A retained index view for consistent pagination, with resource cost and an expiration policy.' },
    { id: 'f8', front: 'Facet semantics', back: 'Define which selected filters apply to each count so alternative filter values are interpreted consistently.' },
    { id: 'f9', front: 'Listing cache identity', back: 'Include query, filters, sort, locale, currency, and any relevant audience context.' },
    { id: 'f10', front: 'Batched hydration', back: 'Fetch current details for result IDs in bounded batches rather than one network call per product.' },
    { id: 'f11', front: 'Parallel index rebuild', back: 'Build and catch up a new index while the old index serves, then switch after verification.' },
    { id: 'f12', front: 'Indexing lag', back: 'Delay between authoritative product changes and their searchable projection. Measure it against the freshness contract.' },
  ],
  feynman: [
    { id: 'fe1', concept: 'Search as a projection', prompt: 'Explain why the store has both a catalog database and search index.', modelExplanation: 'A shop has an official inventory ledger and customer-facing display cards. The ledger records the authoritative product details. The cards arrange the same information so shoppers can quickly find red shoes in their size. A search index plays the display-card role: it is shaped for discovery rather than every transaction the business performs. Changes need to reach the cards reliably, and numbered versions stop an older delivery from replacing a newer card. The cards can lag briefly, so the checkout desk still checks actual price and stock. If the display is damaged, the shop rebuilds it from the ledger. Keeping that rebuild possible is what prevents the search copy from becoming a fragile second source of truth.', mustMention: ['Authoritative write model', 'Read-optimized projection', 'Reliable versioned updates', 'Checkout revalidation and rebuild'] },
    { id: 'fe2', concept: 'Stable pagination', prompt: 'Explain why a bookmark is more than a page number in a changing catalog.', modelExplanation: 'Imagine reading a price-sorted catalog while employees keep moving products as prices change. A page number says how many items to skip, but the items before that position may have changed. A cursor instead records the last product’s complete position, including a unique identifier when prices tie. That avoids some ambiguity, yet a product whose price changes can still move across your bookmark. If the experience promises a stable browsing session, use a snapshot of the catalog edition you started. The snapshot cannot live forever because it consumes resources, so the app must explain when the session expires and let you start again. Stable pagination combines ordering, continuation, and a policy for concurrent changes.', mustMention: ['Offset instability', 'Full sort tuple and tie-breaker', 'Concurrent changes', 'Snapshot expiration'] },
  ],
  memoryPalace: { setting: 'Walk through a shoe store from its window to the directory printing room.', stops: [
    { locus: 'Window', concept: 'Listing contract', image: 'A sign says AVAILABLE RECENTLY while the cashier guards the actual last shoe.' },
    { locus: 'Ledger', concept: 'Source of truth', image: 'An official book sends numbered cards along an outbox conveyor.' },
    { locus: 'Search shelves', concept: 'Projection', image: 'Red shoes jump onto shelves labeled size, price, and brand.' },
    { locus: 'Bookmark', concept: 'Cursor', image: 'A bookmark carries both a price tag and a unique glowing product number.' },
    { locus: 'Travel guide rack', concept: 'Cache keys', image: 'Identical-looking guides print different currencies and languages on their covers.' },
    { locus: 'Print room', concept: 'Rebuild', image: 'A new directory catches up on a conveyor before replacing the old edition.' },
  ] },
  designPractice: { problem: 'Design a read-heavy catalog with ten million products, text search, filters, and stable price-sorted pagination. Listings may lag briefly; checkout must validate price and stock.', steps: [
    { title: 'Requirements', prompt: 'Define product versus variant behavior, filters, and freshness promises.', reference: 'Support text and category browsing, variant-aware filters, price sorting, and product detail links. State a several-second listing freshness target as an exercise assumption. Confirm price and reserve inventory on checkout; define cursor expiry and empty results.' },
    { title: 'Capacity estimation', prompt: 'Assume 100 million listing requests per day, a 10x peak, and 20 KB responses. Estimate traffic.', reference: 'Average is about 1,157 requests/s; a 10x peak is about 11,574 requests/s. At 20 KB per response, peak response payload is about 231 MB/s using decimal units, excluding images and protocol overhead. Ten million 2 KB search documents are about 20 GB before index overhead and replicas.' },
    { title: 'API', prompt: 'Specify a listing request and its pagination response.', reference: 'GET /products?q=shoes&size=9&sort=price_asc&cursor=... returns cards, defined facet counts, and nextCursor. Bind cursors to the query and complete sort tuple, with a point-in-time identifier when required. Reject incompatible or expired cursors explicitly.' },
    { title: 'Data model', prompt: 'Separate authoritative records from search documents.', reference: 'Products and variants have stable IDs, owner/category attributes, source versions, and lifecycle state. Price and inventory have authoritative records. Search documents denormalize searchable fields. An outbox records versioned changes and deletions alongside catalog transactions.' },
    { title: 'High-level design', prompt: 'Trace writes and listing reads.', reference: 'Catalog API -> database plus outbox -> relay -> indexer -> search index. Listing API -> query validation -> cache/search -> batched card hydration -> response. Media uses object storage and CDN. Checkout follows authoritative price and reservation services.' },
    { title: 'Deep dive', prompt: 'Explain pagination and out-of-order indexing.', reference: 'Use price plus product ID for deterministic ordering and search-after within a retained point-in-time view. Expire snapshots. Indexers compare source versions so retries and delayed updates cannot regress data; preserve deletion ordering and reconcile discrepancies.' },
    { title: 'Failure modes', prompt: 'Handle indexing lag, rebuilds, and search outages.', reference: 'Monitor source-to-index lag and replay failed events. Rebuild beside the active index from a snapshot plus subsequent changes; verify before alias switch. Serve permitted cached results during trouble without silently ignoring filters. Recheck purchase invariants regardless of index health.' },
  ] },
  interviewQuestions: ['Why separate the catalog database from its search index?', 'How do you guarantee product changes reach the index?', 'How do you paginate consistently while prices change?', 'What belongs in a listing cache key?', 'How do you rebuild an index without losing concurrent updates?'],
}

export default chapter
