import type { Chapter } from '../types'

const chapter: Chapter = {
  id: 26, slug: 'designing-rate-limiter', title: 'Designing Rate Limiter', module: 'case-studies',
  estimatedMinutes: 40,
  summary: 'Design rate limits with explicit identities, burst rules, and failure policies. Compare window and bucket algorithms, make shared decisions atomic, and bound the uncertainty introduced by multiple regions.',
  objectives: ['Choose a limiting key and quota contract.', 'Compare fixed windows, sliding windows, and token buckets.', 'Implement atomic shared-state decisions.', 'Reason about limiter outages, retries, and regional budgets.'],
  quickRevision: ['Define who is limited, which operation counts, and when tokens are consumed.', 'Rate limits bound arrivals; concurrency limits bound in-flight work.', 'A fixed window is simple but allows boundary bursts.', 'A sliding log is precise for its window but stores individual timestamps.', 'A sliding counter approximates recent traffic with bounded state.', 'A token bucket refills at rate r and caps saved credit at capacity B.', 'Token buckets permit bursts while limiting sustained use.', 'Read-check-update must be one atomic operation.', 'Use a trusted time source and handle nonmonotonic clock movement.', 'Fail-open or fail-closed is an endpoint-specific product decision.', 'Regional token budgets trade exact global limits for latency and availability.', 'Return useful retry guidance without encouraging synchronized retries.'],
  sections: [
    { id: 'policy', title: 'Define the limit before the algorithm',
      body: `A policy such as one hundred requests per minute is incomplete. Identify the subject: account, API key, tenant, device, or IP address. Then identify the action: every API call, a particular expensive endpoint, or a weighted cost such as ten units for a report and one for a lookup. Shared IP addresses can represent many legitimate users, while attackers can rotate IPs, so IP-only policies have important fairness limitations.

Decide when usage is charged. Counting admitted attempts protects service capacity even if the operation later fails. Counting only successful business actions may better express a product allowance but requires coordination with completion and retry semantics. These are different policies and can coexist as separate limits.

Rate limiting also differs from concurrency limiting. Ten requests per second can still produce thousands of simultaneous requests if each runs for several minutes. A concurrency cap bounds active work, while a rate policy controls arrivals over time. Expensive services often need both. Define rejection status, retry guidance, and the behavior of unauthenticated callers before selecting a storage engine.`,
      mentalModel: 'A museum controls how many tickets a visitor buys per day and how many people are inside at once. Those are two different counters.',
      diagram: 'Request -> identity + endpoint + cost\n        -> rate policy -> concurrency admission -> handler\n                    \-> reject with retry guidance',
      keyPoints: ['Define identity, action, cost, and charging point.', 'IP limits have fairness and evasion tradeoffs.', 'Rate and concurrency limits solve different overload risks.'],
      checkpoint: { question: 'An endpoint permits ten requests per second, each taking one minute. Can rate limiting alone keep concurrency below one hundred?', answer: 'No. Sustained traffic can create roughly six hundred active requests. Add a concurrency limit or change processing behavior.' } },
    { id: 'algorithms', title: 'Windows and buckets express different promises',
      body: `A fixed-window counter tracks requests in an aligned interval. It is cheap, but a client can send its full allowance just before a boundary and another full allowance immediately after. If the requirement is no more than one hundred requests in any rolling minute, a fixed calendar-minute counter does not enforce that exact contract.

A sliding log stores timestamps and removes those outside the current interval before counting. It represents a rolling window precisely under the chosen clock and atomicity assumptions, but state and work grow with traffic. A sliding-window counter combines a few buckets to approximate recent usage with less state, accepting error near boundaries.

A token bucket stores available credit. Tokens refill at rate r up to capacity B, and a request with cost c is admitted only when at least c tokens exist. This permits a bounded initial burst and a long-run rate. Over an interval of length T, an initially full bucket can admit at most roughly B plus r times T units. A leaky-bucket shaper instead smooths output, commonly using a bounded queue and scheduled release.`,
      mentalModel: 'A token bucket is a wallet receiving coins steadily, with a maximum savings limit. A fixed window is a fresh envelope of coins every minute.',
      diagram: 'Token bucket: refill r/sec -> [ up to B tokens ]\nRequest cost c -> consume c if available -> admit\nOtherwise -> reject; wait approximately deficit / r',
      keyPoints: ['Match the algorithm to the stated burst contract.', 'Sliding logs trade precision for state.', 'Token buckets bound saved credit and sustained use.'],
      checkpoint: { question: 'A bucket has capacity 20, refills 5 tokens/s, and is full. Can it admit 20 one-token requests immediately?', answer: 'Yes. That is the allowed burst. After spending them, continued admission depends on the five-token-per-second refill.' } },
    { id: 'atomic-state', title: 'Make the decision and update indivisible',
      body: `Two gateway instances can inspect the same remaining token and both admit a request if reading and decrementing are separate operations. The limiter then allows more work than its own policy. Perform refill calculation, admission check, token consumption, and timestamp update as one atomic operation against the key. A Redis script or an appropriate transactional compare-and-update operation can provide this local decision boundary.

Use a consistent time source for shared state. Calculate elapsed time defensively if the clock appears to move backward, and cap refilled credit at the bucket capacity. Floating-point or fixed-point arithmetic should be chosen deliberately when requests have fractional costs. Store enough precision that repeated small refills do not create systematic over-admission.

Expire idle state only when recreating it cannot grant more credit than the policy permits. For a token bucket, an inactivity interval long enough to refill completely is a useful basis. Multi-policy requests, such as per-user and per-tenant limits, need an explicit contract too: consuming one allowance and then failing another may be acceptable for attempt limits, or may require atomic reservation and rollback across the relevant state.`,
      mentalModel: 'The guard must take the last ticket while admitting its holder. Two guards cannot both look at the ticket and promise it before either removes it.',
      diagram: 'Atomic decision(key):\n  elapsed -> refill -> cap at B\n  enough tokens? -> consume -> store -> allow\n              no -> store refill state -> deny',
      keyPoints: ['Do not split check and decrement.', 'Coordinate time and arithmetic.', 'TTL and multi-policy charging affect correctness.'],
      checkpoint: { question: 'Two servers read remaining=1 before either writes. Both allow a request. What failed?', answer: 'The read-check-update sequence was not atomic. Execute the decision and state change together on the authoritative limiter state.' } },
    { id: 'distributed-limits', title: 'Choose where the authoritative budget lives',
      body: `A local in-memory limiter is fast and survives a shared-store outage, but each instance owns only its local view. If every instance grants the full account allowance, adding instances multiplies effective quota. Dividing a fixed allowance equally also has a drawback: a client routed unevenly may be rejected on one instance while unused budget remains elsewhere.

A shared regional store offers a more coordinated decision at the cost of a network hop and dependency. Partition keys distribute unrelated identities, but a single extremely hot tenant can still contend on one key. Local coarse admission can reduce abuse before requests reach the shared exact check, provided the combined policy is documented.

Across regions, a strict globally shared limit requires coordination that affects latency and behavior during network partitions. An alternative is to allocate bounded regional token budgets. The sum of allocations limits possible spending, while reallocation needs careful accounting so the same credit is not leased twice. State the tolerated overshoot or underutilization. Calling asynchronously replicated counters globally exact hides a real consistency tradeoff.`,
      mentalModel: 'Several branches cannot each spend the entire company allowance. They either phone one cashier or receive nonoverlapping envelopes of budget.',
      keyPoints: ['Local limits depend on routing and fleet size.', 'Shared state adds coordination cost.', 'Regional budgets need bounded, nonduplicated allocation.'],
      checkpoint: { question: 'Three regions each allow 100 requests/s for an account advertised as globally limited to 100 requests/s. Is the policy enforced?', answer: 'No. The combined allowance can reach 300 requests/s. Coordinate one global budget or allocate regional shares with an explicit approximation contract.' } },
    { id: 'failure-and-operations', title: 'Choose failure behavior for each endpoint',
      body: `If the shared limiter is unavailable, failing open preserves request availability but may expose the backend to overload or abuse. Failing closed preserves enforcement but can reject legitimate traffic. The choice depends on the endpoint: a low-cost public read may use a conservative local fallback, while a sensitive or expensive operation may require an authoritative decision. Document the degraded policy before an outage forces an accidental default.

When rejecting for quota, return an appropriate response such as HTTP 429 with useful retry information. Retry-After should reflect when another attempt may be useful, while clients still need jitter and an overall deadline. Do not promise a precise successful retry time if other concurrent requests may consume the next available credit.

Measure allowed and denied traffic by policy, decision latency, store errors, hot keys, and fallback activation. Avoid exporting unbounded identity labels into metrics. Test simultaneous attempts against one remaining token, fixed-window boundary bursts, clock movement, idle expiry, and regional allocation changes. Also load-test the limiter itself: admission control becomes a bottleneck if every protected request must wait behind a saturated decision service.`,
      mentalModel: 'When the ticket computer fails, each entrance needs a rehearsed rule: close, use a small emergency booklet, or admit freely with known consequences.',
      keyPoints: ['Make failure mode endpoint-specific.', 'Give useful but honest retry guidance.', 'Test races, boundaries, and degraded behavior.'],
      checkpoint: { question: 'Does Retry-After guarantee the next request will succeed at that exact time?', answer: 'No. It is retry guidance. Other requests may consume available capacity, and the service may still be degraded.' } },
  ],
  quiz: [
    { type: 'mcq', id: 'q1', difficulty: 2, question: 'Which algorithm permits a bounded burst and steady refill?', options: ['An unbounded queue', 'Random rejection only', 'Token bucket', 'A DNS cache'], answerIndex: 2, explanation: 'Capacity controls accumulated burst credit and refill rate controls sustained admission.' },
    { type: 'mcq', id: 'q2', difficulty: 2, question: 'What is a fixed-window weakness?', options: ['Bursts around interval boundaries', 'It cannot count integers', 'It always needs every request timestamp', 'It prevents all bursts'], answerIndex: 0, explanation: 'Two adjacent windows can each spend their full allowance close to the shared boundary.' },
    { type: 'mcq', id: 'q3', difficulty: 3, question: 'What prevents two servers spending the last token?', options: ['Longer key names', 'Atomic check and consumption', 'A browser timeout', 'Reading from two asynchronous replicas'], answerIndex: 1, explanation: 'One authoritative atomic decision serializes competing claims. Separate reads and writes can race.' },
    { type: 'mcq', id: 'q4', difficulty: 2, question: 'What bounds active long-running work?', options: ['A locale filter', 'A request ID alone', 'A cache TTL alone', 'A concurrency limit'], answerIndex: 3, explanation: 'Arrival rate alone does not cap simultaneous work when execution time is long.' },
    { type: 'multi', id: 'q5', difficulty: 2, question: 'Which belong in a rate-limit policy?', options: ['Identity and endpoint', 'Request cost and burst allowance', 'Failure behavior', 'Only the choice of Redis version'], answerIndices: [0, 1, 2], explanation: 'The behavioral contract precedes implementation technology.' },
    { type: 'truefalse', id: 'q6', difficulty: 2, statement: 'Giving every instance the full quota enforces that quota globally.', answer: false, explanation: 'Independent allowances can multiply with fleet size.' },
    { type: 'truefalse', id: 'q7', difficulty: 2, statement: 'A limiter outage must have the same fail-open policy for every endpoint.', answer: false, explanation: 'Availability, abuse risk, and resource cost vary by endpoint.' },
    { type: 'truefalse', id: 'q8', difficulty: 1, statement: 'A sliding log stores individual recent request timestamps.', answer: true, explanation: 'This enables precise rolling-window counting but consumes state proportional to tracked traffic.' },
    { type: 'short', id: 'q9', difficulty: 3, question: 'Describe an atomic token-bucket decision.', modelAnswer: 'Read tokens and last refill time within one atomic operation. Compute nonnegative elapsed time, refill up to capacity, compare against request cost, and decrement only if admitted. Store the resulting tokens and timestamp and set a safe idle expiry. Return allow or deny with estimated retry delay.', rubric: ['Atomic operation', 'Refill capped at capacity', 'Cost comparison and consumption', 'Time and expiry handling'] },
    { type: 'short', id: 'q10', difficulty: 3, question: 'Design a multi-region quota without claiming impossible local exactness.', modelAnswer: 'Choose strict shared coordination or allocate nonoverlapping regional budgets whose sum respects the global allowance. Define lease accounting, reallocation, and partition behavior. Document underutilization or bounded overshoot and use endpoint-specific fallback during coordinator failure.', rubric: ['Coordination tradeoff', 'Budget accounting', 'Partition and reallocation behavior', 'Explicit approximation or failure contract'] },
  ],
  flashcards: [
    { id: 'f1', front: 'Limiting key', back: 'Identity plus policy scope, such as account and endpoint. IP-only keys can group unrelated users and be evaded.' },
    { id: 'f2', front: 'Rate versus concurrency', back: 'Rate bounds arrivals over time. Concurrency bounds work currently in flight.' },
    { id: 'f3', front: 'Fixed window', back: 'Count within aligned intervals. Simple, but full allowances on either side of a boundary create bursts.' },
    { id: 'f4', front: 'Sliding log', back: 'Store recent timestamps for exact rolling-window accounting under the chosen atomicity and clock assumptions.' },
    { id: 'f5', front: 'Sliding counter', back: 'Approximate a recent window using a bounded number of counters, trading precision for lower state.' },
    { id: 'f6', front: 'Token bucket', back: 'Refill credit at rate r up to capacity B; consume request cost when enough credit exists.' },
    { id: 'f7', front: 'Token-bucket interval bound', back: 'An initially full bucket admits at most about B + rT units in time T, subject to implementation precision.' },
    { id: 'f8', front: 'Atomic admission', back: 'Refill, compare, consume, and update state together so concurrent callers cannot spend the same token.' },
    { id: 'f9', front: 'Idle-state expiry', back: 'Recreating expired state must not grant more credit than the policy permits; account for refill-to-full time.' },
    { id: 'f10', front: 'Regional budgets', back: 'Allocate bounded shares of global credit. Avoid duplicate leasing and document reallocation and partition behavior.' },
    { id: 'f11', front: 'Fail-open versus fail-closed', back: 'Continue without authoritative enforcement or reject without it. Choose per endpoint, possibly with conservative local fallback.' },
    { id: 'f12', front: 'Retry-After', back: 'Guidance on when another attempt may be useful, not a guarantee that concurrent demand will leave capacity available.' },
  ],
  feynman: [
    { id: 'fe1', concept: 'Token bucket', prompt: 'Explain burst capacity and sustained rate using pocket money.', modelExplanation: 'Imagine a wallet that receives five coins every second but can hold only twenty. Each request costs one coin. If you have waited long enough, you can spend twenty coins immediately. After that burst, you must wait for new coins to arrive. This is different from getting a fresh envelope of one hundred coins at the start of every minute, which lets you spend one envelope just before a boundary and the next immediately after. The wallet separates how much credit can be saved from how quickly credit returns. A shared wallet also needs one indivisible spending operation: two people cannot both inspect the last coin and each promise to spend it. That is the role of atomic limiter state.', mustMention: ['Refill rate', 'Capacity and burst', 'Fixed-window distinction', 'Atomic spending'] },
    { id: 'fe2', concept: 'Distributed quotas', prompt: 'Explain why local quotas do not automatically form one global quota.', modelExplanation: 'Suppose a company has a daily budget of one hundred pounds and three branch offices. Giving each office permission to spend one hundred creates a potential total of three hundred. To keep one company-wide budget, the offices can ask a central cashier before spending, or receive separate envelopes whose combined value is one hundred. The central cashier provides coordination but adds waiting and becomes a dependency. Envelopes work during disconnection but can leave one office short while another has unused money. Moving money between envelopes requires careful records so the same money is not assigned twice. A multi-region rate limiter has the same choices. State the intended precision, availability, and reallocation behavior instead of assuming fast local counters are globally exact.', mustMention: ['Independent limits multiply', 'Shared coordinator tradeoff', 'Bounded allocations', 'Safe reallocation and explicit guarantees'] },
  ],
  memoryPalace: { setting: 'Tour a museum ticket office with several regional entrances.', stops: [
    { locus: 'Identity desk', concept: 'Policy key', image: 'A guard compares account badges while a hundred visitors share one giant IP-address coat.' },
    { locus: 'Minute clock', concept: 'Fixed-window burst', image: 'Two envelopes explode with tickets on opposite sides of midnight.' },
    { locus: 'Coin fountain', concept: 'Token bucket', image: 'Five coins fall each second into a twenty-coin wallet; extra coins spill away.' },
    { locus: 'One-ticket lockbox', concept: 'Atomicity', image: 'Two guards reach for one ticket but a lock admits only one hand.' },
    { locus: 'Branch map', concept: 'Regional budget', image: 'Three envelopes share one hundred glowing coins without duplicating them.' },
    { locus: 'Emergency gate', concept: 'Failure policy', image: 'One entrance uses a small emergency booklet while a sensitive exhibit remains closed.' },
  ] },
  designPractice: { problem: 'Design an API limiter with per-account token buckets, weighted endpoint costs, and multiple gateways. State how a multi-region version changes the guarantees.', steps: [
    { title: 'Requirements', prompt: 'Define identity, costs, burst behavior, and failure policy.', reference: 'Use authenticated account plus policy ID, charge admitted attempts, and define token costs per endpoint. Example: refill 100 tokens/s with capacity 200. Add concurrency limits for long work. Select failure behavior per endpoint and document retry responses.' },
    { title: 'Capacity estimation', prompt: 'Assume 100,000 decisions/s and one million active keys. Estimate state and traffic.', reference: 'At an assumed 100 bytes of logical state per key, raw state is 100 MB before key, allocator, replication, and database overhead. One shared decision per request means 100,000 state operations/s; measure hot-key concentration and network latency before assigning shard counts.' },
    { title: 'API', prompt: 'Define a limiter decision request and response.', reference: 'Internal check(subject, policyId, cost) returns allowed, remaining credit, and retry guidance. Gateways derive trusted identity and policy rather than accepting arbitrary client claims. Denied HTTP requests use 429; store failure follows the endpoint policy.' },
    { title: 'Data model', prompt: 'Specify token state and policy configuration.', reference: 'State key includes subject and policy version; value stores tokens and last refill time. Configuration stores refill rate, capacity, cost rules, and failure mode. Choose a safe idle TTL and define what a policy-version change does to existing credit.' },
    { title: 'High-level design', prompt: 'Place local and shared checks on the request path.', reference: 'Gateway authenticates -> coarse local abuse protection -> authoritative shared atomic bucket -> concurrency admission -> handler. Partition unrelated keys across the state tier. Metrics aggregate by policy without unbounded account labels.' },
    { title: 'Deep dive', prompt: 'Write the decision arithmetic and discuss multiple policies.', reference: 'available = min(B, tokens + max(0, now-last)*r). Admit only when available >= cost, then subtract cost atomically and persist time. Define whether failed later checks still charge an attempt; stronger all-or-nothing multi-key policies need explicit coordination.' },
    { title: 'Failure modes', prompt: 'Handle store loss, clock movement, and regional partitions.', reference: 'Use bounded decision deadlines and endpoint-specific fail-closed or conservative local fallback. Clamp negative elapsed time and test clock effects. For regions choose shared exact coordination or nonduplicated allocated budgets with a stated approximation contract; never grant the full global quota independently everywhere.' },
  ] },
  interviewQuestions: ['How do fixed windows, sliding windows, and token buckets differ?', 'How do you make a distributed limiter decision atomic?', 'When does a rate limiter also need a concurrency limiter?', 'How do you enforce a multi-region quota?', 'What should happen when the limiter store is unavailable?'],
}

export default chapter
