import type { Chapter } from '../types'

const chapter: Chapter = {
  id: 30, slug: 'designing-twitter-trends', title: 'Designing Twitter Trends', module: 'case-studies',
  estimatedMinutes: 40,
  summary: 'Design a Twitter-style trending-topic system from an event stream. Define trend scoring, event-time windows, distributed aggregation, and abuse resistance without claiming that raw counts or local top lists are sufficient.',
  objectives: ['Define a trend score and geographic scope.', 'Aggregate events with explicit late-data and deduplication rules.', 'Compute distributed top topics without losing global candidates.', 'Handle hot topics, manipulation, and recovery.'],
  quickRevision: ['A trend is unusual recent attention, not necessarily the largest lifetime count.', 'State the topic normalization and geographic scope.', 'Event time describes when an action happened; processing time describes arrival.', 'Watermarks express progress assumptions, not proof that no late event exists.', 'Choose window size, slide, allowed lateness, and correction behavior.', 'Deduplicate accepted events using stable IDs and bounded retention.', 'Aggregate complete per-topic counts before selecting exact global top K.', 'Local top K from arbitrary input partitions can omit a global winner.', 'Hot topics can use partial salted counters followed by a merge.', 'Unique contributors and account limits help resist repeated spam.', 'Publish versioned ranking snapshots for fast reads.', 'Replay needs idempotent or transactional output handling to avoid double counting.'],
  sections: [
    { id: 'what-is-trending', title: 'Popularity and surprise are different rankings',
      body: `A topic mentioned frequently every day may be popular without being newly interesting. A trending-topic feature usually aims to highlight a recent increase in attention within a scope such as a language or region. Begin by defining eligible events, topic extraction, time horizon, and the meaning of a ranking score. This chapter designs an illustrative Twitter-style system, not the internal implementation of any particular company.

A simple score can compare recent unique contributors with a historical baseline. That creates its own edge cases: a topic rising from one mention to five has a large ratio but little broad interest. Require minimum support, smooth tiny denominators, and consider decay so old bursts fade. The exact coefficients are product assumptions that should be evaluated, not universal constants.

Define how hashtags, spelling variants, and language are normalized. Aggressive merging can combine unrelated concepts, while no normalization fragments one topic into many entries. Preserve enough source information to revise extraction rules and replay the pipeline. A useful trend list balances timeliness, relevance, diversity, and resistance to manipulation rather than maximizing a single raw counter.`,
      mentalModel: 'The loudest stadium is not always the newest story. Trending asks which crowd is growing unusually fast and whether enough real people are joining.',
      diagram: 'Eligible events -> normalized topics + region\nRecent attention + baseline + minimum support\n                         -> score -> ranked topics',
      keyPoints: ['Define trend semantics before architecture.', 'Combine growth with minimum support.', 'Treat extraction and scoring as versioned product rules.'],
      checkpoint: { question: 'Why might a topic with 500 mentions outrank one with 10,000?', answer: 'If 500 represents a sharp, credible recent increase while 10,000 is ordinary baseline traffic, a growth-sensitive score may rank the smaller topic higher. The exact rule must be explicit.' } },
    { id: 'time-and-ingestion', title: 'Count when events happened, not just when they arrived',
      body: `Events arrive late because clients disconnect, networks stall, or upstream processing retries. Processing-time windows group by arrival time, which is operationally simple but can misplace a recovered burst into the wrong period. Event-time windows group by the event timestamp, allowing the ranking to reflect when attention actually occurred. Validate timestamps so a faulty client cannot push the clock arbitrarily into the future.

Choose a window length and slide, such as a ten-minute window updated every minute. These are example settings. A watermark indicates the pipeline's estimate of progress through event time and helps decide when to emit results or retire state. It does not prove that an older event can never arrive. Define allowed lateness and whether late events update a published window, enter a correction stream, or are excluded from this ranking.

Persist accepted input in a replayable log and attach stable event IDs. Retries can otherwise count one post multiple times. Deduplication state has a retention cost, so align its lifetime with replay and lateness policies. Log offsets track processing progress; they do not alone guarantee that an external ranking store was updated exactly once.`,
      mentalModel: 'Count applause by the time it happened, not the time the recording reached the studio. A progress marker is a forecast, not a promise that no old tape remains.',
      diagram: 'Event timestamp -> event-time window\nArrival timestamp -> processing-time observation\nWatermark + allowed lateness -> emit / revise / expire',
      keyPoints: ['Event and processing time answer different questions.', 'Watermarks permit progress under a lateness assumption.', 'Deduplication and output recovery need explicit state.'],
      checkpoint: { question: 'A post from 12:00 arrives at 12:08. Must it count as attention at 12:08?', answer: 'Not in an event-time design. It belongs to the window containing 12:00, subject to timestamp validation and the chosen allowed-lateness policy.' } },
    { id: 'aggregation-and-topk', title: 'Aggregate complete topic counts before ranking',
      body: `Partition accepted events by normalized topic and scope so one logical aggregation owner can maintain that topic's window counts. Local partial aggregation can reduce network traffic, but those partials must eventually combine into the complete score for each topic. Store counts in time buckets so advancing a window can add new buckets and remove expired ones without rescanning every event.

Be careful with a tempting shortcut: taking only the top topics from each arbitrary input shard and merging those lists. A topic that is moderately frequent on every shard may be globally dominant while appearing in none of the local top lists. For exact results, compute complete per-topic scores first. If each final topic belongs to one score shard, the union of those shards' top K lists contains the global top K, assuming the same deterministic ordering.

Approximate heavy-hitter sketches can reduce state when the domain is huge, but state the error and candidate-recall implications. Combining a candidate sketch with a later exact count stage may be appropriate. Choose exactness from product needs and measured scale, rather than labeling a lossy local-list merge exact.`,
      mentalModel: 'A candidate can finish second in every neighborhood yet win the city. Keeping only each neighborhood’s winner can erase the true overall winner.',
      diagram: 'Input shards -> partial (topic, window, count)\n             -> topic owners -> complete scores\n             -> per-owner top K -> global merge',
      keyPoints: ['Aggregate by complete topic identity.', 'Arbitrary input-shard top K is unsafe for exact ranking.', 'Approximate methods need an error contract.'],
      checkpoint: { question: 'Shard A has X=6 and A=7; shard B has X=6 and B=7. What goes wrong if each sends only its local winner?', answer: 'The merge sees A=7 and B=7 but misses X=12, the global winner. Aggregate X across input shards before selecting final candidates.' } },
    { id: 'hot-topics-and-abuse', title: 'Scale bursts without rewarding spam',
      body: `A major event can concentrate a large fraction of traffic on one topic. Partitioning by topic keeps aggregation simple but creates a hot owner. Split the hot topic into salted partial counters, then periodically merge those partials into the complete topic score. This trades additional merge work and some update delay for greater ingestion capacity. Preserve stable window and partial identifiers so retries do not add the same partial twice.

Raw mention counts also invite manipulation. Repeated posts from one account should not necessarily contribute the same as independent participation by many users. Limit contributions per account and topic, consider unique contributors, and apply eligibility rules before counting. Approximate distinct-count sketches may help at scale, but their estimation error belongs in ranking evaluation.

Moderation and ranking remain separate controls. A topic can be mathematically popular while inappropriate for a particular surface. Keep the decisions explainable enough to debug: extraction version, eligibility reason, count components, and ranking snapshot should be traceable. Avoid turning high-cardinality raw user identifiers into public metrics; operational visibility should not require exposing the underlying user activity.`,
      mentalModel: 'Several turnstiles count one concert crowd, then report to one scoreboard. One person running through a turnstile repeatedly should not look like a growing audience.',
      keyPoints: ['Salt hot aggregations and merge carefully.', 'Count credible participation, not unlimited repeated actions.', 'Keep ranking and eligibility rules observable.'],
      checkpoint: { question: 'Why does adding more topic partitions fail to fix one extremely hot hashtag?', answer: 'The hashtag still maps to one owner. Split its ingestion into partial counters and merge them, or use another strategy that distributes work for that same logical topic.' } },
    { id: 'serving-and-recovery', title: 'Publish coherent snapshots and recover from replay',
      body: `Readers do not need to query every live counter to display ten trends. The ranking pipeline can periodically publish a small snapshot keyed by region, language, and scoring version. Write the complete snapshot and atomically advance a pointer so clients do not see half of one ranking and half of another. Include an as-of timestamp and define how stale a snapshot may be before the product changes its presentation.

The stream processor should recover its window state and source positions consistently. Updating an external counter and then committing an input offset creates a duplicate-count risk if the worker crashes between them. Use transactional integration where supported or idempotent output records keyed by topic, window, and version. Replaying raw input into a fresh state namespace is useful for backfills and scoring changes.

Monitor end-to-end event delay, late-event rates, duplicate rates, state size, hot partitions, snapshot age, and ranking stability. Test an input burst, a stalled partition, a restarted worker, and a new scoring version. During an outage, a clearly timestamped recent snapshot may be more useful than an empty page, but the allowed stale interval must be intentional.`,
      mentalModel: 'A newsroom publishes a complete dated front page rather than exposing the half-finished editor’s desk to readers.',
      keyPoints: ['Serve small coherent ranking snapshots.', 'Coordinate state recovery with external outputs.', 'Measure freshness and ranking behavior end to end.'],
      checkpoint: { question: 'Why can replay double counts even when input offsets are stored?', answer: 'A worker may update an external result then crash before recording its input progress. Replay repeats the update unless output is transactional or idempotent.' } },
  ],
  quiz: [
    { type: 'mcq', id: 'q1', difficulty: 2, question: 'Which best captures a growth-sensitive trend?', options: ['Only lifetime mentions', 'Recent credible attention relative to baseline', 'Alphabetical ordering', 'The oldest hashtag'], answerIndex: 1, explanation: 'Recent growth with support differs from raw historical popularity.' },
    { type: 'mcq', id: 'q2', difficulty: 2, question: 'What does event time represent?', options: ['When the processor received the event', 'When the cache expired', 'When the action occurred', 'When the ranking page was opened'], answerIndex: 2, explanation: 'Event time belongs to the action itself; arrival is processing time.' },
    { type: 'mcq', id: 'q3', difficulty: 3, question: 'When is merging per-shard top K sufficient for exact global top K?', options: ['After each topic has one complete score on exactly one score shard', 'Whenever input is randomly partitioned', 'Only when all counts are zero', 'When local counts are never combined'], answerIndex: 0, explanation: 'A globally top-K item cannot rank below K items on its own complete-score shard. Arbitrary partial counts do not satisfy that property.' },
    { type: 'mcq', id: 'q4', difficulty: 2, question: 'What can spread ingestion for one hot topic?', options: ['Only more unrelated topic partitions', 'A longer hashtag', 'Deleting timestamps', 'Salted partial counters followed by merging'], answerIndex: 3, explanation: 'Partial ownership distributes work for the same logical key; unrelated partitions do not.' },
    { type: 'multi', id: 'q5', difficulty: 2, question: 'Which need an explicit stream-time policy?', options: ['Window length and slide', 'Allowed lateness', 'Corrections after publication', 'Only the color of the trend badge'], answerIndices: [0, 1, 2], explanation: 'These determine which events affect which results and when state can be retired.' },
    { type: 'truefalse', id: 'q6', difficulty: 2, statement: 'A watermark proves no older event will ever arrive.', answer: false, explanation: 'It expresses progress assumptions; late events can still occur and need a policy.' },
    { type: 'truefalse', id: 'q7', difficulty: 2, statement: 'Repeated posts from one account can distort raw popularity counts.', answer: true, explanation: 'Contribution caps and distinct-user signals reduce simple repetition-based manipulation.' },
    { type: 'truefalse', id: 'q8', difficulty: 2, statement: 'Committing input offsets alone guarantees exactly-once external counter updates.', answer: false, explanation: 'A crash between output and offset commit can repeat the output.' },
    { type: 'short', id: 'q9', difficulty: 3, question: 'Show why merging local winners from input shards can fail.', modelAnswer: 'Shard A has X=6 and A=7; shard B has X=6 and B=7. Each sends its local winner, so X is omitted even though X totals 12. Aggregate complete per-topic scores before selecting exact candidates, or state the approximation error.', rubric: ['Concrete counterexample', 'Explains missing global winner', 'Correct aggregation or approximation contract'] },
    { type: 'short', id: 'q10', difficulty: 3, question: 'Design recovery after a ranking worker crashes.', modelAnswer: 'Restore consistent window state and source progress, then replay retained input. Make output transactional or idempotent by topic/window/version to avoid duplicate counting. Publish coherent snapshots with timestamps, and monitor catch-up lag and late-event handling.', rubric: ['State and source recovery', 'Idempotent or transactional output', 'Coherent snapshots', 'Lag and lateness monitoring'] },
  ],
  flashcards: [
    { id: 'f1', front: 'Trend versus popularity', back: 'A trend emphasizes recent unusual attention, often with minimum support; popularity can simply reflect large baseline volume.' },
    { id: 'f2', front: 'Topic normalization', back: 'Map eligible text or hashtags to consistent topic identities while avoiding incorrect merges across meanings or languages.' },
    { id: 'f3', front: 'Event time', back: 'Timestamp of the underlying action, used to group attention by when it happened.' },
    { id: 'f4', front: 'Watermark', back: 'An estimate of event-time progress used for emitting results and retiring state, not proof that no late event exists.' },
    { id: 'f5', front: 'Allowed lateness', back: 'Policy defining how long older events may revise a window and what happens after that boundary.' },
    { id: 'f6', front: 'Deduplication retention', back: 'How long event identities remain available to reject repeats; align it with replay and lateness expectations.' },
    { id: 'f7', front: 'Unsafe local top K', back: 'Top lists from arbitrary input shards can omit a topic moderately frequent everywhere but globally dominant.' },
    { id: 'f8', front: 'Exact top-K merge condition', back: 'Each topic first has one complete score on one score shard; merge those shards’ top K under the same ordering.' },
    { id: 'f9', front: 'Hot-topic salting', back: 'Split one topic into partial aggregations, then merge their versioned window results.' },
    { id: 'f10', front: 'Unique contributors', back: 'A participation signal less sensitive to repeated messages from one account than raw mention counts.' },
    { id: 'f11', front: 'Ranking snapshot', back: 'A complete versioned top list with scope and as-of time, published coherently for fast reads.' },
    { id: 'f12', front: 'Replay output safety', back: 'Use transactional or idempotent outputs; source offsets alone do not prevent repeated external updates.' },
  ],
  feynman: [
    { id: 'fe1', concept: 'Event-time windows', prompt: 'Explain delayed events and watermarks using recordings of applause.', modelExplanation: 'Suppose several theaters send recordings of their applause to one studio. A recording from noon might arrive eight minutes late because its connection failed. If we count by arrival, we claim the applause happened at eight past noon. Event-time processing uses the recording’s original timestamp instead. But the studio cannot wait forever before publishing a result, so it uses a progress estimate to decide that most earlier recordings should have arrived. That estimate is a watermark. It can be wrong about a very late recording, so the system needs a rule: revise the earlier result within an allowed period, send a correction, or exclude it from that ranking. Timely results and complete historical accuracy require an explicit tradeoff.', mustMention: ['Action time versus arrival', 'Progress estimate', 'Late events remain possible', 'Correction or exclusion policy'] },
    { id: 'fe2', concept: 'Distributed top K', prompt: 'Explain why neighborhood winners may not include the city winner.', modelExplanation: 'In one neighborhood, topic A gets seven votes and X gets six. In another, topic B gets seven votes and X gets six. If each neighborhood reports only its winner, the city sees A and B with seven votes each. Yet X has twelve votes across the city and should win. The mistake is discarding partial evidence before combining it. First send each topic’s contributions to an owner that computes its full score. Once every topic has a complete score on one owner, each owner can safely report its top candidates for the final merge. Approximate sketches are another option when scale demands them, but then we must state what can be missed rather than calling the result exact.', mustMention: ['Concrete distributed counterexample', 'Combine partial topic counts', 'Complete-score ownership', 'Approximation must be explicit'] },
  ],
  memoryPalace: { setting: 'Tour a newsroom covering a citywide festival.', stops: [
    { locus: 'Crowd window', concept: 'Trend score', image: 'A small crowd grows into a giant wave beside an unchanged packed stadium.' },
    { locus: 'Tape desk', concept: 'Event time', image: 'A noon applause tape arrives late wearing its original clock.' },
    { locus: 'Waterline wall', concept: 'Watermark', image: 'A rising line says PROBABLY COMPLETE while one old tape floats past it.' },
    { locus: 'Vote board', concept: 'Global top K', image: 'Two silver medals marked X combine into a giant gold city trophy.' },
    { locus: 'Turnstiles', concept: 'Hot keys and abuse', image: 'Many counters count one concert, while a repeat runner is allowed only one vote.' },
    { locus: 'Printing press', concept: 'Snapshots', image: 'A complete dated front page replaces the old page with one loud stamp.' },
  ] },
  designPractice: { problem: 'Design a Twitter-style regional trends service with a ten-minute event-time window and rankings refreshed every minute. The scoring formula is an explicit exercise choice.', steps: [
    { title: 'Requirements', prompt: 'Define eligible events, scope, freshness, and what counts as a trend.', reference: 'Normalize topics by language and region, count eligible unique participation, and rank recent growth against a smoothed baseline with minimum support. Define ten-minute windows, one-minute refresh, allowed lateness, moderation, and correction behavior.' },
    { title: 'Capacity estimation', prompt: 'Assume 100,000 events/s, 200-byte events, and two topics per event.', reference: 'Raw input is 20 MB/s, about 1.728 TB/day before replication and compression. Topic extraction creates about 200,000 contributions/s. A ten-minute raw window spans 60 million events; aggregate buckets and bounded deduplication reduce retained processing state.' },
    { title: 'API', prompt: 'Specify ranking reads and internal event fields.', reference: 'GET /trends?region=...&language=... returns topics, rank, snapshotVersion, and asOf. Internal events carry eventId, eventTime, ingestionTime, actor reference, scope, and extraction version. Define stale-snapshot behavior explicitly.' },
    { title: 'Data model', prompt: 'Model windows, partials, and ranking output.', reference: 'Key aggregate state by topic, region, language, and time bucket. Deduplication uses event IDs within a stated retention horizon. Hot-topic partials carry stable shard/window versions. Ranking snapshots have a scoring version and coherent publication pointer.' },
    { title: 'High-level design', prompt: 'Trace ingestion through serving.', reference: 'Durable log -> validation/deduplication -> extraction and eligibility -> partial aggregation -> complete per-topic scores -> top-K merge -> snapshot store/cache -> read API. Retain input for recovery and scoring backfills.' },
    { title: 'Deep dive', prompt: 'Explain correct top K and late events.', reference: 'Do not merge only local winners from arbitrary input partitions. Complete each topic score first, then merge score-shard top K. Use event-time windows with watermarks and an explicit allowed-lateness/correction policy; timestamp every published snapshot.' },
    { title: 'Failure modes', prompt: 'Handle worker replay, a hot topic, and coordinated spam.', reference: 'Restore source progress and state consistently with idempotent outputs. Salt hot topics and merge partials without duplicate additions. Limit repeated account contributions and evaluate distinct participation. Serve a bounded stale snapshot during catch-up while monitoring end-to-end lag.' },
  ] },
  interviewQuestions: ['How would you define trending rather than merely popular?', 'How do event time and watermarks affect rankings?', 'Why can local top-K merging miss a global winner?', 'How do you scale a hot topic and resist repeated spam?', 'How do you replay events without corrupting published counts?'],
}

export default chapter
