import type { Chapter } from '../types'

const chapter: Chapter = {
  id: 31, slug: 'designing-url-shorteners', title: 'Designing URL Shorteners', module: 'case-studies',
  estimatedMinutes: 40,
  summary: 'Design short-link creation and fast redirects with explicit uniqueness, expiry, and abuse controls. Compare code allocation strategies and keep analytics outside the critical redirect path.',
  objectives: ['Define creation, redirect, alias, and expiry behavior.', 'Compare random codes with encoded identifiers.', 'Design a cache-backed authoritative lookup path.', 'Handle collisions, hot links, deletion, and asynchronous analytics.'],
  quickRevision: ['A short code identifies a stored mapping; encoding is not encryption.', 'Base62 offers 62^k codes of length k.', 'Random codes still need an atomic uniqueness check and collision retry.', 'Sequential IDs avoid random collisions but reveal structure unless transformed.', 'Custom aliases require atomic reservation in the same namespace.', 'Create retries need idempotency if one logical request should create one link.', 'Choose redirect status and cache policy from whether destinations may change.', 'Check expiry and blocked state on the effective redirect path.', 'Hot links benefit from caching but create invalidation and revocation tradeoffs.', 'Capture click analytics asynchronously so analytics outages do not stop redirects.', 'URL validation and abuse checks protect against malicious destinations.', 'Do not reuse deleted codes casually: old shared links and caches can outlive them.'],
  sections: [
    { id: 'contract', title: 'A short link is a durable public identifier',
      body: `The core service accepts a destination URL and returns a shorter URL containing a code. A browser visiting that code receives a redirect to the destination. Clarify whether links can expire, whether owners can edit destinations, whether custom aliases are allowed, and whether analytics are required. These choices determine cache policy and data lifecycle, not just the creation form.

Restrict accepted schemes to those the service intends to support, commonly HTTP and HTTPS. Parse URLs using a real parser and validate the result. A syntactically valid URL can still point to a malicious destination, so define an abuse-reporting and blocking workflow separately. If the service fetches previews, that fetcher also needs protection from private-network and metadata-service targets.

Treat the code as a public identifier with a long lifetime. People paste it into documents, QR codes, and messages that may survive for years. Reassigning an expired code to an unrelated owner can make those old references lead somewhere unexpected. Decide retention and tombstone behavior before reclaiming the namespace. The simplest reliable contract often starts with immutable destinations and explicit expiration.`,
      mentalModel: 'A short code is a cloakroom ticket. The number tells the clerk which stored destination to return; it does not contain or encrypt the coat.',
      diagram: 'POST destination -> create mapping -> return /abc123\nGET /abc123 -> lookup policy + destination -> HTTP redirect',
      keyPoints: ['Define mutability, expiry, aliases, and analytics.', 'Validate destinations and separate abuse controls.', 'Public identifiers can outlive their database rows.'],
      checkpoint: { question: 'Why is immediately giving an expired code to another customer risky?', answer: 'Old bookmarks, QR codes, and cached redirects may still use that code. Reuse can send existing references to an unrelated destination.' } },
    { id: 'codes-and-collisions', title: 'Allocate codes without trusting probability alone',
      body: `A Base62 alphabet uses digits and upper- and lowercase letters. A code of length k has 62 raised to k possible values. Seven characters provide about 3.52 trillion combinations. This describes namespace size, not a guarantee that randomly generated codes never collide. Use a cryptographically strong random generator when unpredictability matters, then conditionally insert the mapping under a uniqueness constraint. A collision causes a bounded retry with a new code.

Another approach allocates a unique integer and encodes it in Base62. This separates uniqueness from representation and can produce compact codes. A single allocator may become a coordination point, so workers can lease nonoverlapping ranges or use another unique-ID scheme. Sequential structure can make enumeration easier, and encoding the number alone does not hide that structure.

Custom aliases share the same uniqueness problem. Reserve them atomically and reject conflicts; checking availability and later inserting creates a race. Decide case sensitivity and reserve service paths such as api or settings. For creation retries, an idempotency key can map repeated equivalent requests to the same result rather than creating several different valid links.`,
      mentalModel: 'A huge ticket bowl makes accidental duplicates rare, but the clerk still checks the official ticket register before handing one out.',
      diagram: 'Random code -> conditional insert\n                 success -> return\n                 conflict -> new code, bounded retry\nAlternative: unique ID allocation -> Base62 encoding',
      keyPoints: ['Namespace size and uniqueness enforcement differ.', 'Encoding does not provide secrecy.', 'Reserve aliases and retry-created mappings atomically.'],
      checkpoint: { question: 'Two creators generate the same random code at once. What prevents one from overwriting the other?', answer: 'A database uniqueness constraint or atomic conditional insert. The loser generates a new code and retries; a prior availability lookup is insufficient.' } },
    { id: 'lookup-and-cache', title: 'Keep the redirect path short and correct',
      body: `Redirects usually outnumber creations, making the lookup path the main capacity concern. A stateless redirect service checks a cache for the code and falls back to the authoritative mapping store on a miss. The record includes destination, expiry, and lifecycle state such as active, blocked, or deleted. Cache those semantics together so a hit does not bypass expiry or a required blocking decision.

Choose HTTP redirect behavior from the product contract. A permanent redirect can be retained by clients and intermediaries, making later destination changes or revocation difficult to enforce. A temporary redirect with an explicit cache policy provides more control for mutable links. Do not rely solely on a status code to express every caching requirement; configure response headers and test the actual delivery path.

Hot links can receive enormous read traffic. Cache popular mappings and coalesce misses to protect the database, while keeping invalidation behavior aligned with allowed staleness. Negative-cache unknown codes briefly to reduce repeated invalid lookups, but avoid hiding a newly created link behind a long-lived cached miss. The returned destination should come from a trusted stored record, not an unchecked request parameter.`,
      mentalModel: 'A popular ticket lookup can be copied to a front-desk card, but the card must still show whether the ticket has expired or been revoked.',
      diagram: 'GET code -> cache -> active + unexpired? -> redirect\n              | miss\n              v\n       mapping store -> fill cache\nUnknown / expired / blocked -> defined non-redirect response',
      keyPoints: ['Cache the lifecycle contract, not only the URL.', 'Redirect status and headers affect mutability.', 'Bound hot misses and negative-cache lifetime.'],
      checkpoint: { question: 'Why can a permanent cached redirect make a later block ineffective for some users?', answer: 'Their browser or intermediary may redirect using a cached response without contacting the service. Choose cache lifetime and redirect semantics according to the required revocation behavior.' } },
    { id: 'analytics-and-abuse', title: 'Record clicks without delaying every redirect',
      body: `A click event can contain the code, event identifier, timestamp, and a carefully chosen set of request attributes. Publish it asynchronously or use a buffered collection path so a slow analytics warehouse does not block redirects. Decide whether analytics are approximate or whether durable event acceptance is part of the service contract. If the buffer fills, dropping a metric and rejecting a redirect are very different product choices.

Retries, prefetchers, and bots make a click count different from a count of people who intentionally visited a page. Deduplicate where the event contract requires it and label the metric honestly. Aggregate only the data needed for the feature, and keep raw event retention separate from the lifetime of the link mapping. A shortener can work even when detailed analytics are temporarily unavailable.

Abuse controls belong on both creation and redirect paths. Rate-limit bulk creation, support reports, and update blocked state for known harmful links. Destination checks can become stale if the remote page changes. If previews are fetched, isolate that fetcher and validate resolved addresses and redirects. Keep these expensive checks outside the ordinary redirect critical path where the policy permits it.`,
      mentalModel: 'The ticket clerk sends a tally slip to the statistics office after serving the visitor. A jammed statistics printer should not automatically close the cloakroom.',
      keyPoints: ['Separate analytics availability from redirect availability.', 'Clicks are not automatically unique human visits.', 'Creation, redirection, and preview fetching need distinct abuse controls.'],
      checkpoint: { question: 'The analytics consumer is unavailable. Should every redirect return an error?', answer: 'Only if durable analytics acceptance is explicitly part of the product contract. A typical design buffers within limits or records reduced analytics while preserving redirects.' } },
    { id: 'scaling-and-recovery', title: 'Partition by code and preserve identifier history',
      body: `The primary lookup is by short code, so a key-value access pattern is a natural fit. Hash partitioning can spread mappings and requests across storage nodes. A viral code still maps to one logical record, so caching or read replication is needed to spread that record's traffic. Adding storage partitions alone does not divide one hot-key lookup across them.

Creation must acknowledge only after the chosen durability guarantee is met. If the client receives a link whose mapping is lost during failover, the public identifier becomes broken. Define replication, backup, and restore behavior for mappings and any alias reservations. Restoring an old backup also needs to account for deletions and blocks applied afterward, not merely recreate every historical destination.

Expiry can be enforced at read time even before background cleanup removes data. Tombstones or retained code reservations prevent unsafe reuse. Monitor redirect latency, cache misses, lookup errors, expired and blocked requests, collision retries, and analytics backlog. Test a hot-link cache flush, duplicate alias reservation, store failover after creation, and revocation while cached responses exist. These tests connect namespace design to real user behavior.`,
      mentalModel: 'The ticket register is divided into cabinets, but a celebrity’s ticket still needs many front-desk copies. The old ticket number stays reserved after the coat is gone.',
      keyPoints: ['Partition mappings by lookup key.', 'Treat acknowledged code durability as a user promise.', 'Separate read-time expiry from safe cleanup and reuse.'],
      checkpoint: { question: 'Does a nightly expiry cleanup job guarantee expired links cannot redirect during the day?', answer: 'No. The redirect path must check the expiry time. Background cleanup is storage maintenance, not the only enforcement mechanism.' } },
  ],
  quiz: [
    { type: 'mcq', id: 'q1', difficulty: 1, question: 'How many possible length-k Base62 codes exist?', options: ['62 × k', '2^k', 'k^62', '62^k'], answerIndex: 3, explanation: 'Each of k positions independently has 62 choices.' },
    { type: 'mcq', id: 'q2', difficulty: 2, question: 'What guarantees a random code does not replace an existing mapping?', options: ['Atomic uniqueness enforcement', 'A large namespace alone', 'A prior non-atomic lookup', 'A longer destination URL'], answerIndex: 0, explanation: 'A conditional insert or unique constraint resolves concurrent collisions safely.' },
    { type: 'mcq', id: 'q3', difficulty: 2, question: 'Which path should normally be decoupled from redirect latency?', options: ['Mapping lookup', 'Expiry enforcement', 'Analytics aggregation', 'Destination selection'], answerIndex: 2, explanation: 'Analytics can run asynchronously. Lookup and policy enforcement determine the redirect itself.' },
    { type: 'mcq', id: 'q4', difficulty: 2, question: 'Why can permanent redirects complicate editable destinations?', options: ['They disable DNS', 'Clients may retain the old redirect', 'They always erase mappings', 'They prevent HTTPS'], answerIndex: 1, explanation: 'Cached permanent redirects can bypass later server-side changes.' },
    { type: 'multi', id: 'q5', difficulty: 2, question: 'Which fields affect whether a cached mapping may redirect?', options: ['Destination', 'Expiry', 'Blocked/deleted state', 'Only the code color'], answerIndices: [0, 1, 2], explanation: 'The cache must preserve relevant lifecycle and policy fields, not merely the target URL.' },
    { type: 'truefalse', id: 'q6', difficulty: 1, statement: 'Base62 encoding encrypts sequential identifiers.', answer: false, explanation: 'Encoding changes representation, not secrecy or predictability.' },
    { type: 'truefalse', id: 'q7', difficulty: 2, statement: 'Immediate reuse of expired codes can redirect old bookmarks to a new owner.', answer: true, explanation: 'Public references can survive long after expiry, making reuse risky.' },
    { type: 'truefalse', id: 'q8', difficulty: 2, statement: 'A background deletion job alone is sufficient to enforce exact expiry.', answer: false, explanation: 'The read path must check expiry even before cleanup runs.' },
    { type: 'short', id: 'q9', difficulty: 3, question: 'Design safe custom-alias creation with retries.', modelAnswer: 'Validate syntax and reserved names, atomically reserve the alias under a unique key, and return a conflict if occupied. Associate a scoped idempotency key with the accepted creation so compatible retries return the original result. Never overwrite another owner’s alias.', rubric: ['Alias validation', 'Atomic reservation', 'Conflict behavior', 'Idempotent creation retries'] },
    { type: 'short', id: 'q10', difficulty: 3, question: 'Handle a viral link when the cache is flushed.', modelAnswer: 'Coalesce misses, bound database fallback concurrency, and warm the hot mapping. Cache its destination and lifecycle fields with a policy matched to expiry and blocking requirements. Keep analytics asynchronous and observe tail latency, source load, and failure rate.', rubric: ['Miss coalescing', 'Bounded source fallback', 'Lifecycle-aware cache', 'Analytics separation and metrics'] },
  ],
  flashcards: [
    { id: 'f1', front: 'Short-link mapping', back: 'A stored association from public code to destination plus ownership, expiry, and lifecycle policy.' },
    { id: 'f2', front: 'Base62 namespace', back: 'Length k offers 62^k combinations; seven characters provide about 3.52 trillion.' },
    { id: 'f3', front: 'Random-code collision handling', back: 'Generate, conditionally insert under uniqueness enforcement, and retry with a new code on conflict.' },
    { id: 'f4', front: 'Encoded sequential ID', back: 'A unique allocator plus Base62 representation avoids random collisions but may expose predictable structure.' },
    { id: 'f5', front: 'Custom alias reservation', back: 'Validate and reserve atomically; a separate availability check followed by insertion can race.' },
    { id: 'f6', front: 'Creation idempotency', back: 'Repeated compatible requests with one operation key return the same accepted link.' },
    { id: 'f7', front: 'Permanent redirect risk', back: 'Clients may cache the destination and bypass later updates or revocation checks.' },
    { id: 'f8', front: 'Read-time expiry', back: 'Check the expiry timestamp on the effective redirect path; cleanup may happen later.' },
    { id: 'f9', front: 'Negative cache', back: 'Briefly cache unknown codes to limit repeated misses, while avoiding long suppression of newly created links.' },
    { id: 'f10', front: 'Asynchronous click analytics', back: 'Collect and aggregate click events separately so slow analytics do not necessarily block redirects.' },
    { id: 'f11', front: 'Code tombstone', back: 'Retained reservation or deletion state that prevents unsafe reassignment of a previously public identifier.' },
    { id: 'f12', front: 'Preview-fetch risk', back: 'Fetching user-supplied destinations can reach unintended networks; isolate fetchers and validate addresses and redirects.' },
  ],
  feynman: [
    { id: 'fe1', concept: 'Codes and uniqueness', prompt: 'Explain why a huge random code space still needs a uniqueness check.', modelExplanation: 'Imagine drawing ticket numbers from an enormous bowl. Drawing the same number as someone else may be unlikely, but unlikely is not impossible. The service must never give one customer a ticket that silently replaces another customer’s destination. It therefore writes the number into an official register that permits each code only once. If the register says the code is already taken, the service draws another number. That check must happen atomically because two workers can draw the same number at the same time. Encoding an already-unique integer is another option, but Base62 only makes the number compact; it does not hide its meaning or make it secret. Namespace design and uniqueness enforcement solve related but separate problems.', mustMention: ['Probability is not uniqueness', 'Atomic register', 'Collision retry', 'Encoding is not encryption'] },
    { id: 'fe2', concept: 'Redirect caching and revocation', prompt: 'Explain why a fast cached redirect can make blocking a link harder.', modelExplanation: 'Suppose a receptionist tells a visitor that ticket ABC always leads to room 12. The visitor writes that instruction down and goes straight to room 12 on every future visit. If the receptionist later blocks the ticket, the visitor may never ask the desk again and therefore never hear the update. Browsers and intermediaries can behave similarly with cached redirects. The service must choose redirect status and cache lifetime based on whether destinations can change and how quickly blocks must take effect. Server-side caches also need the expiry and blocked state, not just the destination. Faster repeated reads are useful, but their independence from the authoritative desk creates a freshness and revocation tradeoff that belongs in the product contract.', mustMention: ['Cached responses can bypass service', 'Mutability and revocation requirements', 'Status and cache lifetime', 'Lifecycle-aware server cache'] },
  ],
  memoryPalace: { setting: 'Walk through a cloakroom with a public ticket desk and archive.', stops: [
    { locus: 'Ticket bowl', concept: 'Code space', image: 'Trillions of glowing tickets spill out, yet two identical ones collide in midair.' },
    { locus: 'Locked register', concept: 'Atomic uniqueness', image: 'Only one pen can claim a ticket number while the other pen receives RETRY.' },
    { locus: 'Front-desk card', concept: 'Cache', image: 'A popular ticket is copied onto a giant card carrying destination and expiry.' },
    { locus: 'Visitor notebook', concept: 'Permanent redirect', image: 'A visitor follows an old handwritten arrow without consulting the newly blocked desk.' },
    { locus: 'Statistics chute', concept: 'Async analytics', image: 'Tally slips slide to another room while the clerk keeps returning coats.' },
    { locus: 'Old-ticket archive', concept: 'No unsafe reuse', image: 'Retired ticket numbers remain behind glass while ancient QR codes knock at the door.' },
  ] },
  designPractice: { problem: 'Design a URL shortener supporting random codes, custom aliases, optional expiry, fast redirects, and click analytics. Begin with immutable destinations and explain the tradeoff if editing is added.', steps: [
    { title: 'Requirements', prompt: 'Specify creation, lookup, expiry, alias conflicts, and abuse behavior.', reference: 'Accept valid HTTP(S) destinations, return a unique public code, support atomically reserved aliases and optional expiry, and reject blocked links. Define creation idempotency, ownership controls, analytics accuracy, and code-retention policy.' },
    { title: 'Capacity estimation', prompt: 'Assume 10 million creates/day and 1 billion redirects/day, with 500-byte mapping records.', reference: 'Average creation is about 116/s and redirects about 11,574/s. A 10x redirect peak is about 115,741/s. Mapping growth is about 5 GB/day or 1.825 TB/year before indexes, replication, and backups. Seven Base62 characters offer about 3.52 trillion possible codes, but random insertion still checks uniqueness.' },
    { title: 'API', prompt: 'Define create and redirect endpoints.', reference: 'POST /links with destination, optional alias, expiresAt, and an idempotency key returns code and shortUrl. GET /:code performs policy-aware redirect or a defined unknown/expired/blocked response. Choose status and Cache-Control according to mutability and revocation needs.' },
    { title: 'Data model', prompt: 'Model mappings, aliases, and analytics.', reference: 'Key mappings by unique code with destination, owner, createdAt, expiresAt, status, and version. Alias reservation shares uniqueness enforcement. Idempotency records bind creation requests to results. Click events live in a separate log; retain tombstones or reservations to prevent unsafe reuse.' },
    { title: 'High-level design', prompt: 'Trace creation and redirect traffic separately.', reference: 'Create API validates and applies abuse limits -> code generator -> conditional durable insert. Redirect API -> cache -> mapping store on miss -> lifecycle check -> redirect. Click events flow asynchronously to aggregation. Partition mappings by code and cache viral links.' },
    { title: 'Deep dive', prompt: 'Explain collision handling and cache correctness.', reference: 'Use strong random generation and atomic insert with bounded retry; custom aliases return conflict. Cache expiry and blocked state alongside destination. Coalesce hot misses, bound fallback load, and keep negative-cache TTL short enough for newly created links.' },
    { title: 'Failure modes', prompt: 'Handle cache loss, ambiguous creation, analytics outage, and revocation.', reference: 'Protect the store with bounded refill and warm popular mappings. Reuse creation idempotency keys after timeouts. Buffer analytics within limits according to its durability contract. Enforce expiry at read time, invalidate server caches, and acknowledge that already-cached client redirects may outlive a server-side block.' },
  ] },
  interviewQuestions: ['How do random codes and encoded unique IDs compare?', 'How do you reserve aliases safely under concurrency?', 'How do redirect status and caching affect editable links?', 'How do you handle viral links and asynchronous analytics?', 'Why should expired codes not be reused casually?'],
}

export default chapter
