import type { Chapter } from '../types'

const chapter: Chapter = {
  id: 35, slug: 'designing-a-web-crawler', title: 'Designing A Web Crawler', module: 'case-studies',
  estimatedMinutes: 40,
  summary: 'Design a bounded, polite crawler with a durable URL frontier. Coordinate per-origin scheduling, duplicate detection, safe fetching, and recrawl priorities while recovering unfinished work after worker failures.',
  objectives: ['Design a durable frontier with per-origin scheduling.', 'Distinguish URL normalization, URL deduplication, and content deduplication.', 'Apply robots rules and bounded fetch policies.', 'Recover worker leases and prioritize recrawls.'],
  quickRevision: ['The frontier stores discovered URLs and decides what to fetch next.', 'Schedule by origin so many workers do not overwhelm one site.', 'Respect applicable robots rules; robots.txt is not authentication.', 'Normalize URLs conservatively because query order and path case can carry meaning.', 'URL deduplication and content deduplication solve different problems.', 'A Bloom filter can reject unseen URLs falsely if used as the only seen-set authority.', 'Revalidate redirects and resolved addresses before each fetch hop.', 'Bound response bytes, decompression, redirects, and fetch duration.', 'Use leases and idempotent results so crashed workers do not lose frontier work.', 'Apply backoff and per-origin concurrency limits during failures.', 'Prioritize recrawls by value, observed change, and host budget.', 'A crawler needs stopping budgets because link spaces can be effectively infinite.'],
  sections: [
    { id: 'scope-and-frontier', title: 'A crawler is a scheduler before it is a downloader',
      body: `A crawler starts from seed URLs, fetches pages, extracts links, and repeats. That small loop hides the main design problem: deciding which discovered URL may be fetched next. The frontier is the durable collection of pending work plus scheduling state. It must represent priority, origin, eligibility time, retry count, and whether a worker currently owns an attempt.

Define the goal before exploring links. A search index, documentation mirror, and price-monitoring crawler have different scopes, freshness needs, and content requirements. This example targets permitted public HTTP(S) pages with static HTML extraction. Browser rendering can be a separate expensive tier for selected pages, rather than a default for every discovered URL.

Set stopping rules such as allowed origins, page count, byte budget, maximum depth, or elapsed time. Websites can expose calendars, faceted navigation, session parameters, and generated paths that create effectively unbounded URL spaces. A durable queue alone does not stop that expansion. Track the source of discovered URLs so operators can identify which pages or extraction rules are creating the most low-value frontier growth.`,
      mentalModel: 'A library expedition needs an itinerary and a return date. Following every sign forever is not a collection strategy.',
      diagram: 'Seeds -> frontier scheduler -> fetch -> parse -> discovered links\n               ^                              |\n               \---- validate + deduplicate ---/',
      keyPoints: ['Make scheduling state durable.', 'Define crawl scope and rendering assumptions.', 'Bound exploration and trace URL discovery.'],
      checkpoint: { question: 'Why can a crawler visit infinitely many URLs on a small site?', answer: 'Generated calendars, query combinations, session IDs, or cyclic navigation can create unbounded distinct URL strings. Apply scope, normalization, and crawl budgets.' } },
    { id: 'politeness-and-robots', title: 'Coordinate requests to each origin',
      body: `A thousand workers can accidentally send a thousand simultaneous requests to one origin unless scheduling coordinates them. Group work by origin and maintain next-eligible-fetch time plus a concurrency budget. An origin includes scheme, host, and port. Additional limits by host or resolved infrastructure may be useful when several origins share one service. Assign one logical scheduling owner or use atomic shared reservations so per-origin rules remain effective across workers.

Fetch and interpret applicable robots.txt rules before requesting restricted paths, using a standards-aware parser and a declared crawler identity. Robots rules communicate crawl permissions; they are not authentication and do not grant access to otherwise protected content. Define caching and error handling for the robots policy. A network failure must not silently be treated as evidence that all paths are allowed.

Honor server pressure signals such as retry guidance, use conservative request rates, and back off on repeated failures. Do not synchronize every origin's retries at the same instant. A priority queue of eligible origins can choose which origin runs next, while a per-origin queue selects its next URL. This two-level structure balances global throughput with local politeness.`,
      mentalModel: 'Many delivery drivers share one appointment book for each house. Hiring more drivers does not create permission to ring the same doorbell faster.',
      diagram: 'Eligible-origin queue -> origin owner / budget\n                          -> URL queue -> one bounded fetch\nrobots policy + nextEligibleAt + concurrency -> admission',
      keyPoints: ['Coordinate politeness across workers.', 'Treat robots policy separately from authentication.', 'Schedule origins as well as individual URLs.'],
      checkpoint: { question: 'Each worker waits one second between requests, but 100 workers target the same host. Is that a one-request-per-second host limit?', answer: 'No. Independent worker delays can still create about 100 requests/s to the host. Coordinate a shared per-origin or host budget.' } },
    { id: 'identity-and-deduplication', title: 'Different URLs can identify the same content',
      body: `Before inserting a discovered URL, resolve relative references against the page's effective base URL, remove fragments when they do not affect the fetched resource, and normalize only transformations known to preserve meaning. Lowercasing a hostname is different from lowercasing an arbitrary path. Sorting or dropping query parameters can also change a server's response, so use domain-specific rules only when justified.

A durable seen set or unique frontier key prevents repeatedly scheduling the same normalized URL. A Bloom filter can reduce expensive negative lookups, but it can report a URL as probably seen when it is actually new. If completeness matters, confirm positive answers against an exact set before discarding the URL. Treat the filter as an accelerator rather than the only source of truth.

Content deduplication happens after fetching. Different URLs can return identical bytes or nearly identical pages. A content hash identifies exact byte duplicates; extracting normalized main content or using similarity methods can detect broader duplication, with a risk of merging distinct pages. Preserve URL-to-content references so deduplicated storage does not erase discovery and provenance information. URL identity and content identity are separate design decisions.`,
      mentalModel: 'Two addresses may lead to copies of the same book. First avoid revisiting the same address; later decide whether the books themselves are duplicates.',
      diagram: 'Discovered URL -> conservative normalization -> exact seen set\nFetched bytes -> content hash -> deduplicated blob store\nURL record ---------------------------------> content reference',
      keyPoints: ['Normalize without changing resource meaning.', 'Confirm Bloom positives when completeness matters.', 'Preserve provenance while deduplicating content.'],
      checkpoint: { question: 'Can a Bloom filter be the only visited set if every eligible new page must eventually be crawled?', answer: 'No. False positives can make unseen URLs appear visited and be skipped forever. Confirm probable matches against an exact store or accept an explicit incompleteness tradeoff.' } },
    { id: 'fetch-and-parse', title: 'Treat every response as bounded, untrusted input',
      body: `A fetch worker obtains a leased URL, checks policy, resolves its destination, and performs a bounded HTTP request. Validate the resolved address against the permitted network scope and repeat checks for every redirect. Otherwise a seemingly public URL can redirect into internal services. DNS changes also matter: address validation should be tied to the actual connection target rather than only to an earlier unrelated lookup.

Limit redirects, response bytes, decompressed size, connection time, and total request duration. Content-Length is only a hint; enforce streaming limits even when the header is missing or wrong. Parse only supported content types, and isolate parsers or renderers with appropriate resource limits. A large compressed body or pathological document should consume one bounded attempt, not take down an entire worker pool.

Store the fetch result, effective URL, status, headers needed for recrawl, and a content reference. Parse links from the final response using correct relative-URL resolution, then return candidates through the same scope and deduplication pipeline. Keep downloading, parsing, and indexing separable so a slow parser can be scaled or retried without repeatedly fetching the origin.`,
      mentalModel: 'A courier checks every forwarded address, caps parcel weight, and sends suspicious packages to an isolated inspection room.',
      keyPoints: ['Recheck every redirect and actual network target.', 'Enforce limits on streamed and decompressed data.', 'Separate fetch, parse, and index stages.'],
      checkpoint: { question: 'A permitted URL redirects to a private network address. Should the crawler follow it automatically?', answer: 'No. Validate each redirect target and actual resolved connection address against the crawl’s network policy before fetching.' } },
    { id: 'leases-and-recrawls', title: 'Recover work and spend the next crawl budget wisely',
      body: `A worker can crash after taking a URL or after storing a result but before acknowledging completion. Use expiring leases so unfinished work becomes eligible again. Carry an attempt or lease generation and accept completion only from the current owner, preventing a slow former worker from overwriting newer state after its lease has expired. Result writes should be idempotent because retry is normal, not exceptional.

The frontier is not just a one-time queue. Pages change, disappear, or move. Track previous fetch time, content change history, errors, and server validators such as ETag or Last-Modified. Conditional requests can avoid retransferring unchanged content when the origin supports them. Allocate recrawl effort according to page value, observed change frequency, and the origin's available budget.

Priorities need starvation protection so popular origins do not consume the entire crawl. Bound retries for persistent failures, retain useful error history, and distinguish temporary failures from stable removal. Observe eligible queue age, per-origin rates, lease expiry, duplicate ratios, bytes fetched, and content yield. Recovery tests should include a worker dying after persistence and another continuing the same URL without corrupting the frontier.`,
      mentalModel: 'A borrowed job ticket expires if its courier disappears. A replacement courier gets a newer stamp, and the old stamp can no longer change the delivery register.',
      keyPoints: ['Leases recover unfinished work.', 'Fence stale completions and make results idempotent.', 'Recrawl by value and change within fairness budgets.'],
      checkpoint: { question: 'A worker finishes after its lease expired and another worker already completed the URL. Should its result overwrite the new record?', answer: 'No. Check the lease generation or attempt ownership before accepting completion. A stale worker must not regress current state.' } },
  ],
  quiz: [
    { type: 'mcq', id: 'q1', difficulty: 1, question: 'What is the frontier?', options: ['Only a list of downloaded bytes', 'A CSS parser', 'Durable discovered work and scheduling state', 'A DNS protocol'], answerIndex: 2, explanation: 'The frontier tracks pending URLs, priority, eligibility, and ownership, not merely fetched content.' },
    { type: 'mcq', id: 'q2', difficulty: 2, question: 'What enforces politeness across many workers?', options: ['A shared per-origin scheduling budget', 'Each worker independently sleeping', 'More simultaneous sockets', 'Ignoring redirects'], answerIndex: 0, explanation: 'Independent delays do not bound aggregate traffic to the same origin.' },
    { type: 'mcq', id: 'q3', difficulty: 2, question: 'Which normalization is unsafe without domain knowledge?', options: ['Resolving a relative URL', 'Lowercasing every path and dropping all query parameters', 'Parsing the hostname', 'Separating the fragment from a fetch URL'], answerIndex: 1, explanation: 'Paths and query parameters may distinguish resources. Aggressive normalization can erase valid pages.' },
    { type: 'mcq', id: 'q4', difficulty: 3, question: 'What prevents a former lease owner from regressing completed work?', options: ['An old user-agent string', 'A larger response buffer', 'A Bloom filter alone', 'Checking the current lease generation on completion'], answerIndex: 3, explanation: 'A generation or fencing check rejects completion from an expired owner.' },
    { type: 'multi', id: 'q5', difficulty: 2, question: 'Which should be bounded during fetching?', options: ['Redirect count', 'Decompressed response size', 'Total fetch duration', 'Only the URL font size'], answerIndices: [0, 1, 2], explanation: 'Each is a resource-exhaustion or runaway-work boundary.' },
    { type: 'truefalse', id: 'q6', difficulty: 1, statement: 'robots.txt is an authentication mechanism.', answer: false, explanation: 'It communicates crawl rules and does not grant access to protected resources.' },
    { type: 'truefalse', id: 'q7', difficulty: 2, statement: 'A Bloom-only seen set can cause an unseen URL to be skipped.', answer: true, explanation: 'False positives report some new URLs as probably present.' },
    { type: 'truefalse', id: 'q8', difficulty: 2, statement: 'Content deduplication and URL deduplication are the same operation.', answer: false, explanation: 'Different URLs can return identical content; the two stages address different identities.' },
    { type: 'short', id: 'q9', difficulty: 3, question: 'Design safe recovery when a crawler worker crashes.', modelAnswer: 'Lease URLs with an expiry and generation, store results idempotently, and return expired work to eligibility. Accept completion only for the current lease generation. Keep origin concurrency accounting recoverable and test a crash after persistence but before acknowledgment.', rubric: ['Expiring durable lease', 'Idempotent result', 'Stale-owner fencing', 'Recoverable origin budget'] },
    { type: 'short', id: 'q10', difficulty: 3, question: 'How do you prevent a crawl from being trapped by infinite faceted navigation?', modelAnswer: 'Set origin, depth, URL, byte, and time budgets. Normalize conservatively, detect low-value repeated patterns, and trace discovery sources. Use exact URL deduplication plus content deduplication, and allocate recrawl priorities so generated paths cannot starve useful pages.', rubric: ['Explicit stopping budgets', 'Conservative normalization and pattern handling', 'URL and content deduplication', 'Fair prioritization'] },
  ],
  flashcards: [
    { id: 'f1', front: 'Frontier', back: 'Durable URLs plus priority, origin, eligibility time, retry state, and worker ownership.' },
    { id: 'f2', front: 'Origin', back: 'Scheme, hostname, and port. It is a useful scheduling scope, with additional host or infrastructure limits when needed.' },
    { id: 'f3', front: 'Politeness coordination', back: 'A shared schedule and concurrency budget prevent many workers from overwhelming one origin.' },
    { id: 'f4', front: 'Robots rules', back: 'Crawl permissions communicated through robots.txt; they are not authentication or authorization to bypass protected access.' },
    { id: 'f5', front: 'Conservative URL normalization', back: 'Apply only meaning-preserving transformations. Path case and query parameters can distinguish resources.' },
    { id: 'f6', front: 'Bloom filter caveat', back: 'False positives can skip unseen URLs. Confirm probable matches against exact state if completeness matters.' },
    { id: 'f7', front: 'Content hash', back: 'Identifies exact byte duplicates after fetching; preserve URL references even when sharing stored content.' },
    { id: 'f8', front: 'Redirect validation', back: 'Recheck policy and resolved connection addresses for every hop, not only the initial URL.' },
    { id: 'f9', front: 'Fetch limits', back: 'Bound redirects, bytes, decompression, connection time, total duration, and parser resources.' },
    { id: 'f10', front: 'Worker lease', back: 'Temporary ownership of frontier work. Expiration enables recovery; generation checks reject stale completion.' },
    { id: 'f11', front: 'Conditional recrawl', back: 'Use stored ETag or Last-Modified validators where supported to avoid retransferring unchanged content.' },
    { id: 'f12', front: 'Crawl trap', back: 'Generated calendars, parameters, or paths create unbounded low-value work. Scope and stopping budgets are essential.' },
  ],
  feynman: [
    { id: 'fe1', concept: 'Polite distributed scheduling', prompt: 'Explain why adding crawler workers requires shared scheduling.', modelExplanation: 'Imagine a hundred delivery drivers visiting the same house. Each driver waits one second before ringing again, but the residents still hear a hundred doorbells per second. A delay inside each worker does not create a house-wide limit. The drivers need one shared appointment book for that address. A crawler similarly groups URLs by origin, checks its crawl rules, and allows requests only when that origin’s budget permits. A global scheduler chooses among origins that are ready, while each origin has its own queue of pages. More workers then improve throughput across different sites without increasing pressure on one site beyond the intended limit. Failures and retries must use the same schedule rather than bypassing it in a separate emergency loop.', mustMention: ['Independent worker limits multiply', 'Shared per-origin budget', 'Two-level scheduling', 'Retries obey the same policy'] },
    { id: 'fe2', concept: 'URL versus content identity', prompt: 'Explain why a crawler needs more than one kind of deduplication.', modelExplanation: 'A library may list the same book at several addresses. Before traveling, you want to avoid visiting exactly the same address repeatedly. That is URL deduplication. After arriving, you may discover that two different addresses hold identical books. That is content deduplication. Normalizing an address too aggressively can also be wrong: removing an apartment number may merge two genuinely different destinations. URLs have similar details in their paths and query parameters. A compact Bloom filter can quickly suggest that an address was seen, but it occasionally says yes for a new address. If the crawl must be complete, verify that suggestion against an exact register. Keep the relationship between each URL and its content even when storing only one copy of identical bytes.', mustMention: ['URL identity before fetch', 'Content identity after fetch', 'Conservative normalization', 'Bloom false positives and exact confirmation'] },
  ],
  memoryPalace: { setting: 'Join a library expedition through an appointment office and archive.', stops: [
    { locus: 'Itinerary board', concept: 'Frontier', image: 'URLs stand in dated queues with priority flags and borrowed job tickets.' },
    { locus: 'Doorbell desk', concept: 'Politeness', image: 'A hundred drivers share one appointment book so only one bell rings at a time.' },
    { locus: 'Permission sign', concept: 'Robots', image: 'A sign marks permitted aisles but cannot unlock a private door.' },
    { locus: 'Address mirror', concept: 'Deduplication', image: 'Two addresses reflect the same book while a false Bloom alarm is checked against a real register.' },
    { locus: 'Parcel scale', concept: 'Bounded fetching', image: 'A tiny compressed parcel inflates until a strict weight gate stops it.' },
    { locus: 'Stamped ticket rack', concept: 'Lease recovery', image: 'An expired courier stamp crumbles when it tries to overwrite a newer delivery receipt.' },
  ] },
  designPractice: { problem: 'Design a polite crawler for permitted public HTML pages, with one billion target pages, bounded daily fetching, durable recovery, and change-aware recrawling.', steps: [
    { title: 'Requirements', prompt: 'Define scope, robots behavior, rendering, and stopping rules.', reference: 'Crawl permitted public HTTP(S) HTML within configured origins and budgets. Respect applicable robots rules, use a declared identity, bound per-origin traffic, and begin with static parsing. Specify page/byte/time budgets, freshness goals, and a separate optional rendering tier.' },
    { title: 'Capacity estimation', prompt: 'Assume 100 million pages/day averaging 100 KB compressed transfer.', reference: 'Average fetch rate is about 1,157 pages/s and payload throughput about 116 MB/s, or 10 TB/day in decimal units. One billion stored pages average about 100 TB before deduplication, versions, replication, and metadata. Origin politeness and response latency constrain actual concurrency more than totals alone.' },
    { title: 'API and worker contract', prompt: 'Specify work leasing and completion.', reference: 'leaseNext(workerId) returns URL, origin policy, lease generation, and deadline. complete(urlId, generation, resultRef) succeeds only for current ownership. Seed submission is authenticated and scope-validated. Fetch results include effective URL, status, timestamp, validators, and content reference.' },
    { title: 'Data model', prompt: 'Model frontier, origins, and fetched content.', reference: 'Frontier records normalized URL, origin, priority, nextEligibleAt, retries, state, and lease generation. Origin records hold robots policy, scheduling budget, and backoff. Fetch records reference content hashes and retained validators; exact seen state preserves URL identity and discovery provenance.' },
    { title: 'High-level design', prompt: 'Trace a full crawl cycle.', reference: 'Seed intake -> validation and exact deduplication -> per-origin frontier -> eligible-origin scheduler -> bounded fetch workers -> object storage -> parsers -> discovered links and index output. Recrawl scheduling feeds existing URLs back through the same origin policy.' },
    { title: 'Deep dive', prompt: 'Explain distributed politeness and duplicate handling.', reference: 'Use one logical owner or atomic reservations for each origin’s request budget. Expiring worker leases recover work and generation checks fence stale completions. Normalize URLs conservatively; use Bloom filters only as accelerators if completeness matters, and hash fetched bytes separately for content deduplication.' },
    { title: 'Failure modes', prompt: 'Handle worker death, traps, hostile responses, and origin errors.', reference: 'Recover expired leases with idempotent results, bound retries with jitter and backoff, and obey the same origin schedule on retries. Stop crawl traps with scope and budgets. Revalidate every redirect and actual destination address; cap streamed and decompressed bytes and isolate parsers. Monitor queue age, lease expiry, per-origin rate, and useful-content yield.' },
  ] },
  interviewQuestions: ['How do you coordinate politeness across many crawler workers?', 'How do URL normalization and content deduplication differ?', 'Why can a Bloom-only visited set reduce completeness?', 'How do you recover leased work without stale overwrites?', 'How do you bound crawl traps, fetch resources, and recrawl effort?'],
}

export default chapter
